#####  areatrigger_tavern  #####

SET NAMES 'utf8';
UPDATE areatrigger_tavern SET name='Westfall - Späherkuppe Gasthaus' WHERE id=71;
UPDATE areatrigger_tavern SET name='Schlingendorntal - Nesingwarys Expedition' WHERE id=98;
UPDATE areatrigger_tavern SET name='Alteracgebirge - Strahnbrad' WHERE id=178;
UPDATE areatrigger_tavern SET name='Wald von Elwynn - Goldhain - Gasthaus zur Höhle des Löwen' WHERE id=562;
UPDATE areatrigger_tavern SET name='Rotkammgebirge - Gasthaus Seenhain' WHERE id=682;
UPDATE areatrigger_tavern SET name='Dämmerwald - Dunkelhain - Taverne Zum roten Raben' WHERE id=707;
UPDATE areatrigger_tavern SET name='Vorgebirge des Hügellands - Gasthaus von Süderstade' WHERE id=708;
UPDATE areatrigger_tavern SET name='Düstermarschen - Die Insel Theramore' WHERE id=709;
UPDATE areatrigger_tavern SET name='Dun Morogh - Kharanos - Brauerei Donnerbräu' WHERE id=710;
UPDATE areatrigger_tavern SET name='Loch Modan - Thelsamar - Gasthof zum Starkbierlager' WHERE id=712;
UPDATE areatrigger_tavern SET name='Sumpfland - Hafen von Menethil - Tiefenwassertaverne' WHERE id=713;
UPDATE areatrigger_tavern SET name='Teldrassil - Dolanaar' WHERE id=715;
UPDATE areatrigger_tavern SET name='Dunkelküste - Auberdine' WHERE id=716;
UPDATE areatrigger_tavern SET name='Eschental - Astranaar' WHERE id=717;
UPDATE areatrigger_tavern SET name='Tirisfal - Brill - Taverne Zur Galgenschlinge' WHERE id=719;
UPDATE areatrigger_tavern SET name='Silberwald - Das Grabmal' WHERE id=720;
UPDATE areatrigger_tavern SET name='Vorgebirge des Hügellands - Tarrens Mühle' WHERE id=721;
UPDATE areatrigger_tavern SET name='Mulgore - Dorf der Bluthufe' WHERE id=722;
UPDATE areatrigger_tavern SET name='Brachland - Das Wegekreuz' WHERE id=742;
UPDATE areatrigger_tavern SET name='Brachland - Ratschet' WHERE id=743;
UPDATE areatrigger_tavern SET name='Durotar - Klingenhügel' WHERE id=843;
UPDATE areatrigger_tavern SET name='Sümpfe des Elends - Steinard' WHERE id=844;
UPDATE areatrigger_tavern SET name='Schlingendorntal - Beutebucht - Taverne zum salzigen Seemann' WHERE id=862;
UPDATE areatrigger_tavern SET name='Brachland - Camp Taurajo' WHERE id=982;
UPDATE areatrigger_tavern SET name='Steinkrallengebirge - Sonnenfels' WHERE id=1022;
UPDATE areatrigger_tavern SET name='Tanaris - Gadgetzan' WHERE id=1023;
UPDATE areatrigger_tavern SET name='Feralas - Mondfederfeste' WHERE id=1024;
UPDATE areatrigger_tavern SET name='Feralas - Camp Mojache' WHERE id=1025;
UPDATE areatrigger_tavern SET name='Hinterland - Nistgipfel - Burg Wildhammer' WHERE id=1042;
UPDATE areatrigger_tavern SET name='Ödland - Kargath' WHERE id=1606;
UPDATE areatrigger_tavern SET name='Arathihochland - Hammerfall' WHERE id=1646;
UPDATE areatrigger_tavern SET name='Desolace - Die Nijelspitze' WHERE id=2266;
UPDATE areatrigger_tavern SET name='Desolace - Schattenflucht' WHERE id=2267;
UPDATE areatrigger_tavern SET name='Tausend Nadeln - Freiwindposten' WHERE id=2286;
UPDATE areatrigger_tavern SET name='Winterquell - Ewige Warte' WHERE id=2287;
UPDATE areatrigger_tavern SET name='Eschental - Splitterholzposten' WHERE id=2610;
UPDATE areatrigger_tavern SET name='Sturmwind - Eingang' WHERE id=2786; -- Gasthaus?
UPDATE areatrigger_tavern SET name='Unterstadt - Eingang' WHERE id=3547; -- Gasthaus?
UPDATE areatrigger_tavern SET name='Hinterland - Dorf der Bruchhauer' WHERE id=3690;
UPDATE areatrigger_tavern SET name='Schlingendorntal - Basislager von Grom\'gol' WHERE id=3886;
UPDATE areatrigger_tavern SET name='Silithus - Burg Cenarius' WHERE id=3985;
UPDATE areatrigger_tavern SET name='Östliche Pestländer - Kapelle des hoffnungsvollen Lichts' WHERE id=4058;
UPDATE areatrigger_tavern SET name='Steinkrallengebirge - Der Steinkrallengipfel' WHERE id=4090;
UPDATE areatrigger_tavern SET name='Geisterlande - Gasthaus von Tristessa' WHERE id=4108;
UPDATE areatrigger_tavern SET name='Geisterlande - Oberes Gasthaus von Tristessa' WHERE id=4109;
UPDATE areatrigger_tavern SET name='Azurmythosinsel - Gasthaus der Azurwacht' WHERE id=4240;
UPDATE areatrigger_tavern SET name='Blutmythosinsel - Gasthaus der Blutwacht' WHERE id=4241;
UPDATE areatrigger_tavern SET name='Immersangwald - Gasthaus von Morgenluft' WHERE id=4265;
UPDATE areatrigger_tavern SET name='Zangarmarschen - Gasthaus der Zuflucht des Cenarius - Eingang' WHERE id=4300;
UPDATE areatrigger_tavern SET name='Höllenfeuerhalbinsel - Gasthaus von Thrallmar' WHERE id=4336;
UPDATE areatrigger_tavern SET name='Höllenfeuerhalbinsel - Gasthaus der Ehrenfeste' WHERE id=4337;
UPDATE areatrigger_tavern SET name='Zangarmarschen - Gasthaus von Zabra\'Jin' WHERE id=4373;
UPDATE areatrigger_tavern SET name='Zangarmarschen - Gasthaus von Telredor' WHERE id=4374;
UPDATE areatrigger_tavern SET name='Nagrand - Gasthaus von Garadar' WHERE id=4375;
UPDATE areatrigger_tavern SET name='Nagrand - Gasthaus von Telaar' WHERE id=4376;
UPDATE areatrigger_tavern SET name='Wälder von Terokkar - Gasthaus von Allerias Feste' WHERE id=4377;
UPDATE areatrigger_tavern SET name='Wälder von Terokkar - Gasthaus der Steinbrecherfeste' WHERE id=4378;
UPDATE areatrigger_tavern SET name='Höllenfeuerhalbinsel - Gasthaus der Falkenwacht' WHERE id=4380;
UPDATE areatrigger_tavern SET name='Höllenfeuerhalbinsel - Gasthaus des Temples von Telhamat' WHERE id=4381;
UPDATE areatrigger_tavern SET name='Zangarmarschen - Gasthaus der Zuflucht des Cenarius' WHERE id=4382;
UPDATE areatrigger_tavern SET name='Zangarmarschen - Gasthaus der Oreborzuflucht' WHERE id=4383;
UPDATE areatrigger_tavern SET name='Immersangwald - Gasthaus des Falkenplatzes' WHERE id=4486;
UPDATE areatrigger_tavern SET name='Schergrat - Gasthaus der Donnerfeste' WHERE id=4494;
UPDATE areatrigger_tavern SET name='Höhlen der Zeit - Vorgebirge des alten Hügellands - Gasthaus von Süderstade' WHERE id=4498;
UPDATE areatrigger_tavern SET name='Schergrat - Gasthaus von Sylvanaar' WHERE id=4499;
UPDATE areatrigger_tavern SET name='Nethersturm - Gasthaus der Area 52' WHERE id=4521;
UPDATE areatrigger_tavern SET name='Schattenmondtal - Gasthaus von Schattenmond' WHERE id=4526;
UPDATE areatrigger_tavern SET name='Schattenmondtal - Gasthaus der Wildhammerfeste' WHERE id=4528;
UPDATE areatrigger_tavern SET name='Nethersturm - Gasthaus der Sturmsäule' WHERE id=4555;
UPDATE areatrigger_tavern SET name='Schergrat - Gasthaus von Toshleys Station' WHERE id=4558;
UPDATE areatrigger_tavern SET name='Schattenmondtal - Gasthaus des Altars der Sha\'tar' WHERE id=4577;
UPDATE areatrigger_tavern SET name='Schergrat - Gasthaus vom Dorf der Mok\'Nathal' WHERE id=4595;
UPDATE areatrigger_tavern SET name='Schattenmondtal - Gasthaus des Sanktums der Sterne' WHERE id=4607;
UPDATE areatrigger_tavern SET name='Schattenmondtal - Oberes Gasthaus des Sanktums der Sterne' WHERE id=4608;
UPDATE areatrigger_tavern SET name='Schergrat - Gasthaus des Ewigen Hains' WHERE id=4640;
UPDATE areatrigger_tavern SET name='Düstermarschen - Gasthaus des Morastwinkels' WHERE id=4714;
UPDATE areatrigger_tavern SET name='Der heulende Fjord - Gasthaus der Westwacht' WHERE id=4753;
UPDATE areatrigger_tavern SET name='Der heulende Fjord - Gasthaus des Lagers der Winterhufe' WHERE id=4755;
UPDATE areatrigger_tavern SET name='Der heulende Fjord - Gasthaus von Fort Wildervar' WHERE id=4756;
UPDATE areatrigger_tavern SET name='Eisenschmiede - Eingang' WHERE id=4769; -- Gasthaus?
UPDATE areatrigger_tavern SET name='Düstermarschen - Gasthaus von Brackenwall' WHERE id=4775;
UPDATE areatrigger_tavern SET name='Insel von Quel\'Danas - Gasthof vom Hafen der Sonnenweiten' WHERE id=4847;
UPDATE areatrigger_tavern SET name='Boreanische Tundra - Gasthaus des Außenpostens Bor\'gorok' WHERE id=4861;
UPDATE areatrigger_tavern SET name='Boreanische Tundra - Gasthaus der Landebahn Kurbelzisch' WHERE id=4867;
UPDATE areatrigger_tavern SET name='Boreanische Tundra - Gasthaus von Taunka\'le' WHERE id=4868;
UPDATE areatrigger_tavern SET name='Boreanische Tundra - Kriegshymnenfeste' WHERE id=4910;
UPDATE areatrigger_tavern SET name='Boreanische Tundra - Gasthaus der Valianzfeste' WHERE id=4961;
UPDATE areatrigger_tavern SET name='Drachenöde - Sternenruh' WHERE id=4964;
UPDATE areatrigger_tavern SET name='Grizzlyhügel - Gasthaus der Ammertannhütte' WHERE id=4965;
UPDATE areatrigger_tavern SET name='Grizzlyhügel - Lager der Westfallbrigade' WHERE id=4966;
UPDATE areatrigger_tavern SET name='Grizzlyhügel - Camp Oneqwah' WHERE id=4967;
UPDATE areatrigger_tavern SET name='Grizzlyhügel - Burg Siegeswall' WHERE id=4970;
UPDATE areatrigger_tavern SET name='Drachenöde - Hafen Moa\'ki' WHERE id=4975;
UPDATE areatrigger_tavern SET name='Der heulende Fjord - Kamagua' WHERE id=4976;
UPDATE areatrigger_tavern SET name='Boreanische Tundra - Gasthaus von Unu\'pe' WHERE id=4977;
UPDATE areatrigger_tavern SET name='Drachenöde - Gallgrimm' WHERE id=4979;
UPDATE areatrigger_tavern SET name='Drachenöde - Feste Wintergarde' WHERE id=4993;
UPDATE areatrigger_tavern SET name='Sholazarbecken - Lager der Speerträger' WHERE id=5030; -- Gasthaus?
UPDATE areatrigger_tavern SET name='Drachenöde - Agmars Hammer' WHERE id=5045;
UPDATE areatrigger_tavern SET name='Zul\'Drak - Die Argentumwache' WHERE id=5062;
UPDATE areatrigger_tavern SET name='Zul\'Drak - Zim\'Torga' WHERE id=5164;
UPDATE areatrigger_tavern SET name='Die Sturmgipfel - Eisfestung' WHERE id=5182;
UPDATE areatrigger_tavern SET name='Die Sturmgipfel - K3' WHERE id=5183;
UPDATE areatrigger_tavern SET name='Die Sturmgipfel - Brunnhildar' WHERE id=5200;
UPDATE areatrigger_tavern SET name='Die Sturmgipfel - Bergfels\' Zuflucht' WHERE id=5204;
UPDATE areatrigger_tavern SET name='Sholazarbecken - Nesingwarys Basislager' WHERE id=5217;
UPDATE areatrigger_tavern SET name='Eiskrone - Die Argentumvorhut' WHERE id=5227;
UPDATE areatrigger_tavern SET name='Drachenöde - Wyrmruhtempel Westen' WHERE id=5314; -- Gasthaus?
UPDATE areatrigger_tavern SET name='Drachenöde - Wyrmruhtempel Norden' WHERE id=5315; -- Gasthaus?
UPDATE areatrigger_tavern SET name='Drachenöde - Wyrmruhtempel Osten' WHERE id=5316; -- Gasthaus?
UPDATE areatrigger_tavern SET name='Drachenöde - Wyrmruhtempel Süden' WHERE id=5317; -- Gasthaus?
UPDATE areatrigger_tavern SET name='Die Sturmgipfel - Camp Tunka\'lo' WHERE id=5323;
UPDATE areatrigger_tavern SET name='Dalaran - Krasus\' Landeplatz' WHERE id=5327;
SET NAMES 'latin1';
