#####  game_event  #####

SET NAMES 'utf8';
UPDATE game_event SET description='Sonnenwendfest' WHERE entry=1;
UPDATE game_event SET description='Winterhauchfest' WHERE entry=2;
UPDATE game_event SET description='Dunkelmond-Jahrmarkt (Wälder von Terokkar)' WHERE entry=3;
UPDATE game_event SET description='Dunkelmond-Jahrmarkt (Wald von Elwynn)' WHERE entry=4;
UPDATE game_event SET description='Dunkelmond-Jahrmarkt (Mulgore)' WHERE entry=5;
UPDATE game_event SET description='Neujahr' WHERE entry=6;
UPDATE game_event SET description='Mondfest' WHERE entry=7;
UPDATE game_event SET description='Liebe liegt in der Luft' WHERE entry=8;
UPDATE game_event SET description='Piratentag' WHERE entry=9;
UPDATE game_event SET description='Kinderwoche' WHERE entry=10;
UPDATE game_event SET description='Erntedankfest' WHERE entry=11;
UPDATE game_event SET description='Schlotternächte' WHERE entry=12;
UPDATE game_event SET description='Invasion der Elementare' WHERE entry=13;
UPDATE game_event SET description='Anglerwettbewerb im Schlingendorntal Aufruf' WHERE entry=14;
UPDATE game_event SET description='Anglerwettbewerb im Schlingendorntal' WHERE entry=15;
UPDATE game_event SET description='Gurubashiarena' WHERE entry=16;
UPDATE game_event SET description='Invasion der Geißel' WHERE entry=17;
UPDATE game_event SET description='Ruf zu den Waffen: Alteractal!' WHERE entry=18;
UPDATE game_event SET description='Ruf zu den Waffen: Kriegshymnenschlucht!' WHERE entry=19;
UPDATE game_event SET description='Ruf zu den Waffen: Arathibecken!' WHERE entry=20;
UPDATE game_event SET description='Ruf zu den Waffen: Auge des Sturms!' WHERE entry=21;
UPDATE game_event SET description='Krieg von Ahn\'Qiraj' WHERE entry=22;
UPDATE game_event SET description='Dunkelmond-Jahrmarkt wird aufgebaut 2 (Wald von Elwynn)' WHERE entry=23;
UPDATE game_event SET description='Angelwettstreit der Kalu\'ak' WHERE entry=24;
UPDATE game_event SET description='Ruf zu den Waffen: Strand der Uralten' WHERE entry=25;
UPDATE game_event SET description='Braufest' WHERE entry=26;
UPDATE game_event SET description='Nacht beginnt' WHERE entry=27;
UPDATE game_event SET description='Nobelgartenfest' WHERE entry=28;
UPDATE game_event SET description='Rand des Wahnsinns, Gri\'lek' WHERE entry=29;
UPDATE game_event SET description='Rand des Wahnsinns, Hazza\'rah' WHERE entry=30;
UPDATE game_event SET description='Rand des Wahnsinns, Renataki' WHERE entry=31;
UPDATE game_event SET description='Rand des Wahnsinns, Wushoolay' WHERE entry=32;
UPDATE game_event SET description='Arenaturnier' WHERE entry=33;
UPDATE game_event SET description='L70ETC Konzert' WHERE entry=34;
UPDATE game_event SET description='Tag der Toten' WHERE entry=35;
UPDATE game_event SET description='Anglerwettbewerb im Schlingendorntal beginnt' WHERE entry=36;
UPDATE game_event SET description='Pilgerfreudenfest' WHERE entry=37;
UPDATE game_event SET description='Ruf zu den Waffen: Insel der Eroberung!' WHERE entry=38;
UPDATE game_event SET description='Angelwettstreit der Kalu\'ak (Ankündigung)' WHERE entry=39;
UPDATE game_event SET description='Angelwettstreit der Kalu\'ak (Endet)' WHERE entry=40;
UPDATE game_event SET description='Die Anführer in Jin\'Alai, Kutube\'sa' WHERE entry=41;
UPDATE game_event SET description='Die Anführer in Jin\'Alai, Gawanil' WHERE entry=42;
UPDATE game_event SET description='Die Anführer in Jin\'Alai, Chulo' WHERE entry=43;
UPDATE game_event SET description='Bier des Monats - Januar' WHERE entry=45;
UPDATE game_event SET description='Bier des Monats - Februar' WHERE entry=46;
UPDATE game_event SET description='Bier des Monats - März' WHERE entry=47;
UPDATE game_event SET description='Bier des Monats - April' WHERE entry=48;
UPDATE game_event SET description='Bier des Monats - Mai' WHERE entry=49;
UPDATE game_event SET description='Bier des Monats - Juni' WHERE entry=50;
UPDATE game_event SET description='Bier des Monats - Juli' WHERE entry=51;
UPDATE game_event SET description='Bier des Monats - August' WHERE entry=52;
UPDATE game_event SET description='Bier des Monats - September' WHERE entry=53;
UPDATE game_event SET description='Bier des Monats - Oktober' WHERE entry=54;
UPDATE game_event SET description='Bier des Monats - November' WHERE entry=55;
UPDATE game_event SET description='Bier des Monats - Dezember' WHERE entry=56;
UPDATE game_event SET description='Taverne Weltenend - Hel\'gesh Neider (Ankündigung)' WHERE entry=57;
UPDATE game_event SET description='Taverne Weltenend - Hel\'gesh Neider Komödienauftritt' WHERE entry=58;
UPDATE game_event SET description='Taverne Weltenend - L70ETC Konzert (Ankündigung)' WHERE entry=59;
UPDATE game_event SET description='Taverne Weltenend - L70ETC Konzert' WHERE entry=60;
UPDATE game_event SET description='Sturmwind - Verlies Gefängnisausbruch' WHERE entry=61;
UPDATE game_event SET description='Dunkelmond-Jahrmarkt wird aufgebaut 1 (Wälder von Terokkar)' WHERE entry=62;
UPDATE game_event SET description='Dunkelmond-Jahrmarkt wird aufgebaut 2 (Wälder von Terokkar)' WHERE entry=63;
UPDATE game_event SET description='Dunkelmond-Jahrmarkt wird aufgebaut 1 (Mulgore)' WHERE entry=64;
UPDATE game_event SET description='Dunkelmond-Jahrmarkt wird aufgebaut 2 (Mulgore)' WHERE entry=65;
UPDATE game_event SET description='Dunkelmond-Jahrmarkt wird aufgebaut 1 (Wald von Elwynn)' WHERE entry=66;
SET NAMES 'latin1';
