#####  game_event  #####

SET NAMES 'utf8';
UPDATE game_event SET description='Sonnenwendfest' WHERE entry=1;
UPDATE game_event SET description='Winterhauchfest' WHERE entry=2;
UPDATE game_event SET description='Dunkelmond-Jahrmarkt (Wälder von Terokkar)' WHERE entry=3;
UPDATE game_event SET description='Dunkelmond-Jahrmarkt (Wald von Elwynn)' WHERE entry=4;
UPDATE game_event SET description='Dunkelmond-Jahrmarkt (Mulgore)' WHERE entry=5;
UPDATE game_event SET description='Neujahrsfeier' WHERE entry=6;
UPDATE game_event SET description='Mondfest' WHERE entry=7;
UPDATE game_event SET description='Liebe liegt in der Luft' WHERE entry=8;
UPDATE game_event SET description='Winterhauchfest - Geschenke' WHERE entry=9;
UPDATE game_event SET description='Kinderwoche' WHERE entry=10;
UPDATE game_event SET description='Erntedankfest' WHERE entry=11;
UPDATE game_event SET description='Schlotternächte' WHERE entry=12;
UPDATE game_event SET description='Invasion der Elementare' WHERE entry=13;
UPDATE game_event SET description='Anglerwettbewerb im Schlingendorntal (Aufruf)' WHERE entry=14;
UPDATE game_event SET description='Anglerwettbewerb im Schlingendorntal' WHERE entry=15;
UPDATE game_event SET description='Gurubashiarena' WHERE entry=16;
UPDATE game_event SET description='Invasion der Geißel' WHERE entry=17;
UPDATE game_event SET description='Ruf zu den Waffen: Alteractal!' WHERE entry=18;
UPDATE game_event SET description='Ruf zu den Waffen: Kriegshymnenschlucht!' WHERE entry=19;
UPDATE game_event SET description='Ruf zu den Waffen: Arathibecken!' WHERE entry=20;
UPDATE game_event SET description='Ruf zu den Waffen: Auge des Sturms!' WHERE entry=21;
UPDATE game_event SET description='Krieg von Ahn\'Qiraj' WHERE entry=22;
UPDATE game_event SET description='Dunkelmond-Jahrmarkt wird aufgebaut 2 (Wald von Elwynn)' WHERE entry=23;
UPDATE game_event SET description='Angelwettstreit der Kalu\'ak' WHERE entry=24;
UPDATE game_event SET description='Ruf zu den Waffen: Strand der Uralten!' WHERE entry=25;
UPDATE game_event SET description='Braufest' WHERE entry=26;
UPDATE game_event SET description='Nacht beginnt' WHERE entry=27;
UPDATE game_event SET description='Nobelgartenfest' WHERE entry=28;
UPDATE game_event SET description='Zul\'Gurub, Rand des Wahnsinns, Gri\'lek' WHERE entry=29;
UPDATE game_event SET description='Zul\'Gurub, Rand des Wahnsinns, Hazza\'rah' WHERE entry=30;
UPDATE game_event SET description='Zul\'Gurub, Rand des Wahnsinns, Renataki' WHERE entry=31;
UPDATE game_event SET description='Zul\'Gurub, Rand des Wahnsinns, Wushoolay' WHERE entry=32;
UPDATE game_event SET description='Arenaturnier' WHERE entry=33;
UPDATE game_event SET description='L70ETC Konzert' WHERE entry=34;
UPDATE game_event SET description='Tag der Toten' WHERE entry=35;
UPDATE game_event SET description='Anglerwettbewerb im Schlingendorntal beginnt' WHERE entry=36;
UPDATE game_event SET description='Pilgerfreudenfest' WHERE entry=37;
UPDATE game_event SET description='Ruf zu den Waffen: Insel der Eroberung!' WHERE entry=38;
UPDATE game_event SET description='Angelwettstreit der Kalu\'ak (Ankündigung)' WHERE entry=39;
UPDATE game_event SET description='Angelwettstreit der Kalu\'ak (Endet)' WHERE entry=40;
UPDATE game_event SET description='Zul\'Drak, Die Anführer in Jin\'Alai, Kutube\'sa' WHERE entry=41;
UPDATE game_event SET description='Zul\'Drak, Die Anführer in Jin\'Alai, Gawanil' WHERE entry=42;
UPDATE game_event SET description='Zul\'Drak, Die Anführer in Jin\'Alai, Chulo der Verrückte' WHERE entry=43;
UPDATE game_event SET description='Piratentag' WHERE entry=44;
UPDATE game_event SET description='Bier des Monats - Januar' WHERE entry=45;
UPDATE game_event SET description='Bier des Monats - Februar' WHERE entry=46;
UPDATE game_event SET description='Bier des Monats - März' WHERE entry=47;
UPDATE game_event SET description='Bier des Monats - April' WHERE entry=48;
UPDATE game_event SET description='Bier des Monats - Mai' WHERE entry=49;
UPDATE game_event SET description='Bier des Monats - Juni' WHERE entry=50;
UPDATE game_event SET description='Bier des Monats - Juli' WHERE entry=51;
UPDATE game_event SET description='Bier des Monats - August' WHERE entry=52;
UPDATE game_event SET description='Bier des Monats - September' WHERE entry=53;
UPDATE game_event SET description='Bier des Monats - Oktober' WHERE entry=54;
UPDATE game_event SET description='Bier des Monats - November' WHERE entry=55;
UPDATE game_event SET description='Bier des Monats - Dezember' WHERE entry=56;
UPDATE game_event SET description='Shattrath, Taverne Weltenend - Hel\'gesh Neider (Ankündigung)' WHERE entry=57;
UPDATE game_event SET description='Shattrath, Taverne Weltenend - Hel\'gesh Neider Komödienauftritt' WHERE entry=58;
UPDATE game_event SET description='Shattrath, Taverne Weltenend - L70ETC Konzert (Ankündigung)' WHERE entry=59;
UPDATE game_event SET description='Shattrath, Taverne Weltenend - L70ETC Konzert' WHERE entry=60;
UPDATE game_event SET description='Sturmwind - Verlies Gefängnisausbruch' WHERE entry=61;
UPDATE game_event SET description='Dunkelmond-Jahrmarkt wird aufgebaut 1 (Wälder von Terokkar)' WHERE entry=62;
UPDATE game_event SET description='Dunkelmond-Jahrmarkt wird aufgebaut 2 (Wälder von Terokkar)' WHERE entry=63;
UPDATE game_event SET description='Dunkelmond-Jahrmarkt wird aufgebaut 1 (Mulgore)' WHERE entry=64;
UPDATE game_event SET description='Dunkelmond-Jahrmarkt wird aufgebaut 2 (Mulgore)' WHERE entry=65;
UPDATE game_event SET description='Dunkelmond-Jahrmarkt wird aufgebaut 1 (Wald von Elwynn)' WHERE entry=66;
UPDATE game_event SET description='Schlotternächte - Glut des Weidenmanns' WHERE entry=67;
UPDATE game_event SET description='Schlotternächte - Bansheekönigin' WHERE entry=68;
-- UPDATE game_event SET description='' WHERE entry=1000;
-- UPDATE game_event SET description='' WHERE entry=1001;
-- UPDATE game_event SET description='' WHERE entry=1002;
-- UPDATE game_event SET description='' WHERE entry=1003;
-- UPDATE game_event SET description='' WHERE entry=1004;
-- UPDATE game_event SET description='' WHERE entry=1005;
-- UPDATE game_event SET description='' WHERE entry=1006;
-- UPDATE game_event SET description='' WHERE entry=1007;
-- UPDATE game_event SET description='' WHERE entry=1008;
-- UPDATE game_event SET description='' WHERE entry=1009;
-- UPDATE game_event SET description='' WHERE entry=1010;
-- UPDATE game_event SET description='' WHERE entry=1011;
-- UPDATE game_event SET description='' WHERE entry=1012;
-- UPDATE game_event SET description='' WHERE entry=1013;
-- UPDATE game_event SET description='' WHERE entry=1014;
-- UPDATE game_event SET description='' WHERE entry=1015;
-- UPDATE game_event SET description='' WHERE entry=1016;
-- UPDATE game_event SET description='' WHERE entry=1017;
-- UPDATE game_event SET description='' WHERE entry=1018;
-- UPDATE game_event SET description='' WHERE entry=1019;
-- UPDATE game_event SET description='' WHERE entry=1020;
-- UPDATE game_event SET description='' WHERE entry=1021;
-- UPDATE game_event SET description='' WHERE entry=1022;
-- UPDATE game_event SET description='' WHERE entry=1023;
-- UPDATE game_event SET description='' WHERE entry=1024;
-- UPDATE game_event SET description='' WHERE entry=1025;
-- UPDATE game_event SET description='' WHERE entry=1026;
-- UPDATE game_event SET description='' WHERE entry=1027;
-- UPDATE game_event SET description='' WHERE entry=1028;
-- UPDATE game_event SET description='' WHERE entry=1029;
-- UPDATE game_event SET description='' WHERE entry=1030;
-- UPDATE game_event SET description='' WHERE entry=1031;
-- UPDATE game_event SET description='' WHERE entry=1032;
-- UPDATE game_event SET description='' WHERE entry=1033;
-- UPDATE game_event SET description='' WHERE entry=1034;
-- UPDATE game_event SET description='' WHERE entry=1035;
-- UPDATE game_event SET description='' WHERE entry=1036;
-- UPDATE game_event SET description='' WHERE entry=1037;
-- UPDATE game_event SET description='' WHERE entry=1038;
-- UPDATE game_event SET description='' WHERE entry=1039;
-- UPDATE game_event SET description='' WHERE entry=1040;
-- UPDATE game_event SET description='' WHERE entry=1041;
-- UPDATE game_event SET description='' WHERE entry=1042;
-- UPDATE game_event SET description='' WHERE entry=1043;
-- UPDATE game_event SET description='' WHERE entry=1044;
-- UPDATE game_event SET description='' WHERE entry=1045;
-- UPDATE game_event SET description='' WHERE entry=1046;
-- UPDATE game_event SET description='' WHERE entry=1047;
-- UPDATE game_event SET description='' WHERE entry=1048;
-- UPDATE game_event SET description='' WHERE entry=1049;
-- UPDATE game_event SET description='' WHERE entry=1050;
-- UPDATE game_event SET description='' WHERE entry=1051;
-- UPDATE game_event SET description='' WHERE entry=1052;
-- UPDATE game_event SET description='' WHERE entry=1053;
-- UPDATE game_event SET description='' WHERE entry=1054;
-- UPDATE game_event SET description='' WHERE entry=1055;
-- UPDATE game_event SET description='' WHERE entry=1056;
-- UPDATE game_event SET description='' WHERE entry=1057;
-- UPDATE game_event SET description='' WHERE entry=1058;
-- UPDATE game_event SET description='' WHERE entry=1059;
-- UPDATE game_event SET description='' WHERE entry=1060;
-- UPDATE game_event SET description='' WHERE entry=1061;
-- UPDATE game_event SET description='' WHERE entry=1062;
-- UPDATE game_event SET description='' WHERE entry=1063;
-- UPDATE game_event SET description='' WHERE entry=1064;
-- UPDATE game_event SET description='' WHERE entry=1065;
-- UPDATE game_event SET description='' WHERE entry=1066;
-- UPDATE game_event SET description='' WHERE entry=1067;
-- UPDATE game_event SET description='' WHERE entry=1068;
-- UPDATE game_event SET description='' WHERE entry=1069;
-- UPDATE game_event SET description='' WHERE entry=1070;
-- UPDATE game_event SET description='' WHERE entry=1071;
-- UPDATE game_event SET description='' WHERE entry=1072;
-- UPDATE game_event SET description='' WHERE entry=1073;
-- UPDATE game_event SET description='' WHERE entry=1074;
-- UPDATE game_event SET description='' WHERE entry=1075;
-- UPDATE game_event SET description='' WHERE entry=1076;
-- UPDATE game_event SET description='' WHERE entry=1077;
-- UPDATE game_event SET description='' WHERE entry=1078;
-- UPDATE game_event SET description='' WHERE entry=1079;
-- UPDATE game_event SET description='' WHERE entry=1080;
-- UPDATE game_event SET description='' WHERE entry=1081;
-- UPDATE game_event SET description='' WHERE entry=1082;
-- UPDATE game_event SET description='' WHERE entry=1083;
-- UPDATE game_event SET description='' WHERE entry=1084;
-- UPDATE game_event SET description='' WHERE entry=1085;
-- UPDATE game_event SET description='' WHERE entry=1086;
-- UPDATE game_event SET description='' WHERE entry=1087;
-- UPDATE game_event SET description='' WHERE entry=1088;
-- UPDATE game_event SET description='' WHERE entry=1089;
-- UPDATE game_event SET description='' WHERE entry=1090;
-- UPDATE game_event SET description='' WHERE entry=1091;
-- UPDATE game_event SET description='' WHERE entry=1092;
-- UPDATE game_event SET description='' WHERE entry=1093;
-- UPDATE game_event SET description='' WHERE entry=1094;
-- UPDATE game_event SET description='' WHERE entry=1095;
-- UPDATE game_event SET description='' WHERE entry=1096;
-- UPDATE game_event SET description='' WHERE entry=1097;
-- UPDATE game_event SET description='' WHERE entry=1098;
-- UPDATE game_event SET description='' WHERE entry=1099;
-- UPDATE game_event SET description='' WHERE entry=1100;
-- UPDATE game_event SET description='' WHERE entry=1101;
-- UPDATE game_event SET description='' WHERE entry=1102;
-- UPDATE game_event SET description='' WHERE entry=1103;
-- UPDATE game_event SET description='' WHERE entry=1104;
-- UPDATE game_event SET description='' WHERE entry=1105;
-- UPDATE game_event SET description='' WHERE entry=1106;
-- UPDATE game_event SET description='' WHERE entry=1107;
-- UPDATE game_event SET description='' WHERE entry=1108;
-- UPDATE game_event SET description='' WHERE entry=1109;
-- UPDATE game_event SET description='' WHERE entry=1110;
-- UPDATE game_event SET description='' WHERE entry=1111;
-- UPDATE game_event SET description='' WHERE entry=1112;
-- UPDATE game_event SET description='' WHERE entry=1113;
-- UPDATE game_event SET description='' WHERE entry=1114;
-- UPDATE game_event SET description='' WHERE entry=1115;
-- UPDATE game_event SET description='' WHERE entry=1116;
-- UPDATE game_event SET description='' WHERE entry=1117;
-- UPDATE game_event SET description='' WHERE entry=1118;
-- UPDATE game_event SET description='' WHERE entry=1119;
-- UPDATE game_event SET description='' WHERE entry=1120;
-- UPDATE game_event SET description='' WHERE entry=1121;
-- UPDATE game_event SET description='' WHERE entry=1122;
-- UPDATE game_event SET description='' WHERE entry=1123;
-- UPDATE game_event SET description='' WHERE entry=1124;
-- UPDATE game_event SET description='' WHERE entry=1125;
-- UPDATE game_event SET description='' WHERE entry=1126;
-- UPDATE game_event SET description='' WHERE entry=1127;
-- UPDATE game_event SET description='' WHERE entry=1128;
-- UPDATE game_event SET description='' WHERE entry=1129;
-- UPDATE game_event SET description='' WHERE entry=1130;
-- UPDATE game_event SET description='' WHERE entry=1131;
-- UPDATE game_event SET description='' WHERE entry=1132;
-- UPDATE game_event SET description='' WHERE entry=1133;
-- UPDATE game_event SET description='' WHERE entry=1134;
-- UPDATE game_event SET description='' WHERE entry=1135;
-- UPDATE game_event SET description='' WHERE entry=1136;
-- UPDATE game_event SET description='' WHERE entry=1137;
-- UPDATE game_event SET description='' WHERE entry=1138;
-- UPDATE game_event SET description='' WHERE entry=1139;
-- UPDATE game_event SET description='' WHERE entry=1140;
-- UPDATE game_event SET description='' WHERE entry=1141;
-- UPDATE game_event SET description='' WHERE entry=1142;
-- UPDATE game_event SET description='' WHERE entry=1143;
-- UPDATE game_event SET description='' WHERE entry=1144;
-- UPDATE game_event SET description='' WHERE entry=1145;
-- UPDATE game_event SET description='' WHERE entry=1146;
-- UPDATE game_event SET description='' WHERE entry=1147;
-- UPDATE game_event SET description='' WHERE entry=1148;
-- UPDATE game_event SET description='' WHERE entry=1149;
-- UPDATE game_event SET description='' WHERE entry=1150;
-- UPDATE game_event SET description='' WHERE entry=1151;
-- UPDATE game_event SET description='' WHERE entry=1152;
-- UPDATE game_event SET description='' WHERE entry=1153;
-- UPDATE game_event SET description='' WHERE entry=1154;
-- UPDATE game_event SET description='' WHERE entry=1155;
-- UPDATE game_event SET description='' WHERE entry=1156;
-- UPDATE game_event SET description='' WHERE entry=1157;
-- UPDATE game_event SET description='' WHERE entry=1158;
-- UPDATE game_event SET description='' WHERE entry=1159;
-- UPDATE game_event SET description='' WHERE entry=1160;
-- UPDATE game_event SET description='' WHERE entry=1161;
-- UPDATE game_event SET description='' WHERE entry=1162;
-- UPDATE game_event SET description='' WHERE entry=1163;
-- UPDATE game_event SET description='' WHERE entry=1164;
-- UPDATE game_event SET description='' WHERE entry=1165;
-- UPDATE game_event SET description='' WHERE entry=1166;
-- UPDATE game_event SET description='' WHERE entry=1167;
-- UPDATE game_event SET description='' WHERE entry=1168;
SET NAMES 'latin1';
