#####  game_event  #####

SET NAMES 'utf8';
UPDATE game_event SET description='Sonnenwendfest' WHERE entry=1;
UPDATE game_event SET description='Winterhauchfest' WHERE entry=2;
UPDATE game_event SET description='Dunkelmond-Jahrmarkt (Wälder von Terokkar)' WHERE entry=3;
UPDATE game_event SET description='Dunkelmond-Jahrmarkt (Wald von Elwynn)' WHERE entry=4;
UPDATE game_event SET description='Dunkelmond-Jahrmarkt (Mulgore)' WHERE entry=5;
UPDATE game_event SET description='Neujahrsfeier' WHERE entry=6;
UPDATE game_event SET description='Mondfest' WHERE entry=7;
UPDATE game_event SET description='Liebe liegt in der Luft' WHERE entry=8;
UPDATE game_event SET description='Winterhauchfest - Geschenke' WHERE entry=9;
UPDATE game_event SET description='Kinderwoche' WHERE entry=10;
UPDATE game_event SET description='Erntedankfest' WHERE entry=11;
UPDATE game_event SET description='Schlotternächte' WHERE entry=12;
UPDATE game_event SET description='Anglerwettbewerb im Schlingendorntal (Aufruf)' WHERE entry=14;
UPDATE game_event SET description='Anglerwettbewerb im Schlingendorntal' WHERE entry=15;
UPDATE game_event SET description='Gurubashiarena' WHERE entry=16;
UPDATE game_event SET description='Invasion der Geißel' WHERE entry=17;
UPDATE game_event SET description='Ruf zu den Waffen: Alteractal!' WHERE entry=18;
UPDATE game_event SET description='Ruf zu den Waffen: Kriegshymnenschlucht!' WHERE entry=19;
UPDATE game_event SET description='Ruf zu den Waffen: Arathibecken!' WHERE entry=20;
UPDATE game_event SET description='Ruf zu den Waffen: Auge des Sturms!' WHERE entry=21;
UPDATE game_event SET description='Krieg von Ahn\'Qiraj' WHERE entry=22;
UPDATE game_event SET description='Dunkelmond-Jahrmarkt wird aufgebaut 2 (Wald von Elwynn)' WHERE entry=23;
UPDATE game_event SET description='Angelwettstreit der Kalu\'ak' WHERE entry=24;
UPDATE game_event SET description='Ruf zu den Waffen: Strand der Uralten!' WHERE entry=25;
UPDATE game_event SET description='Braufest' WHERE entry=26;
UPDATE game_event SET description='Nacht beginnt' WHERE entry=27;
UPDATE game_event SET description='Nobelgartenfest' WHERE entry=28;
UPDATE game_event SET description='Zul\'Gurub, Rand des Wahnsinns, Gri\'lek' WHERE entry=29;
UPDATE game_event SET description='Zul\'Gurub, Rand des Wahnsinns, Hazza\'rah' WHERE entry=30;
UPDATE game_event SET description='Zul\'Gurub, Rand des Wahnsinns, Renataki' WHERE entry=31;
UPDATE game_event SET description='Zul\'Gurub, Rand des Wahnsinns, Wushoolay' WHERE entry=32;
UPDATE game_event SET description='Arenaturnier' WHERE entry=33;
UPDATE game_event SET description='L70ETC Konzert' WHERE entry=34;
UPDATE game_event SET description='Tag der Toten' WHERE entry=35;
UPDATE game_event SET description='Anglerwettbewerb im Schlingendorntal beginnt' WHERE entry=36;
UPDATE game_event SET description='Pilgerfreudenfest' WHERE entry=37;
UPDATE game_event SET description='Ruf zu den Waffen: Insel der Eroberung!' WHERE entry=38;
UPDATE game_event SET description='Angelwettstreit der Kalu\'ak (Ankündigung)' WHERE entry=39;
UPDATE game_event SET description='Angelwettstreit der Kalu\'ak (Endet)' WHERE entry=40;
UPDATE game_event SET description='Zul\'Drak, Die Anführer in Jin\'Alai, Kutube\'sa' WHERE entry=41;
UPDATE game_event SET description='Zul\'Drak, Die Anführer in Jin\'Alai, Gawanil' WHERE entry=42;
UPDATE game_event SET description='Zul\'Drak, Die Anführer in Jin\'Alai, Chulo der Verrückte' WHERE entry=43;
UPDATE game_event SET description='Piratentag' WHERE entry=44;
UPDATE game_event SET description='Bier des Monats - Januar' WHERE entry=45;
UPDATE game_event SET description='Bier des Monats - Februar' WHERE entry=46;
UPDATE game_event SET description='Bier des Monats - März' WHERE entry=47;
UPDATE game_event SET description='Bier des Monats - April' WHERE entry=48;
UPDATE game_event SET description='Bier des Monats - Mai' WHERE entry=49;
UPDATE game_event SET description='Bier des Monats - Juni' WHERE entry=50;
UPDATE game_event SET description='Bier des Monats - Juli' WHERE entry=51;
UPDATE game_event SET description='Bier des Monats - August' WHERE entry=52;
UPDATE game_event SET description='Bier des Monats - September' WHERE entry=53;
UPDATE game_event SET description='Bier des Monats - Oktober' WHERE entry=54;
UPDATE game_event SET description='Bier des Monats - November' WHERE entry=55;
UPDATE game_event SET description='Bier des Monats - Dezember' WHERE entry=56;
UPDATE game_event SET description='Shattrath, Taverne Weltenend - Hel\'gesh Neider (Ankündigung)' WHERE entry=57;
UPDATE game_event SET description='Shattrath, Taverne Weltenend - Hel\'gesh Neider Komödienauftritt' WHERE entry=58;
UPDATE game_event SET description='Shattrath, Taverne Weltenend - L70ETC Konzert (Ankündigung)' WHERE entry=59;
UPDATE game_event SET description='Shattrath, Taverne Weltenend - L70ETC Konzert' WHERE entry=60;
UPDATE game_event SET description='Sturmwind - Verlies Gefängnisausbruch' WHERE entry=61;
UPDATE game_event SET description='Dunkelmond-Jahrmarkt wird aufgebaut 1 (Wälder von Terokkar)' WHERE entry=62;
UPDATE game_event SET description='Dunkelmond-Jahrmarkt wird aufgebaut 2 (Wälder von Terokkar)' WHERE entry=63;
UPDATE game_event SET description='Dunkelmond-Jahrmarkt wird aufgebaut 1 (Mulgore)' WHERE entry=64;
UPDATE game_event SET description='Dunkelmond-Jahrmarkt wird aufgebaut 2 (Mulgore)' WHERE entry=65;
UPDATE game_event SET description='Dunkelmond-Jahrmarkt wird aufgebaut 1 (Wald von Elwynn)' WHERE entry=66;
UPDATE game_event SET description='Schlotternächte - Glut des Weidenmanns' WHERE entry=67;
UPDATE game_event SET description='Schlotternächte - Bansheekönigin' WHERE entry=68;
UPDATE game_event SET description='Before the Storm - TBC-Startereignis' WHERE entry=100;
UPDATE game_event SET description='Invasion der Elementare: Feuer' WHERE entry=200;
UPDATE game_event SET description='Invasion der Elementare: Luft' WHERE entry=201;
UPDATE game_event SET description='Invasion der Elementare: Erde' WHERE entry=202;
UPDATE game_event SET description='Invasion der Elementare: Wasser' WHERE entry=203;
UPDATE game_event SET description='Die Schlacht um die Sonnenweiten Phase 1' WHERE entry=301;
UPDATE game_event SET description='Die Schlacht um die Sonnenweiten Phase 2' WHERE entry=302;
UPDATE game_event SET description='Die Schlacht um die Sonnenweiten Phase 2 Dauerhaft' WHERE entry=303;
UPDATE game_event SET description='Die Schlacht um die Sonnenweiten Phase Kein Portal' WHERE entry=304;
UPDATE game_event SET description='Die Schlacht um die Sonnenweiten Phase Portal' WHERE entry=305;
UPDATE game_event SET description='Die Schlacht um die Sonnenweiten Phase 3' WHERE entry=306;
UPDATE game_event SET description='Die Schlacht um die Sonnenweiten Phase 3 Dauerhaft' WHERE entry=307;
UPDATE game_event SET description='Die Schlacht um die Sonnenweiten Phase Kein Amboss' WHERE entry=308;
UPDATE game_event SET description='Die Schlacht um die Sonnenweiten Phase Amboss' WHERE entry=309;
UPDATE game_event SET description='Die Schlacht um die Sonnenweiten Phase 4' WHERE entry=310;
UPDATE game_event SET description='Die Schlacht um die Sonnenweiten Phase Kein Monument' WHERE entry=311;
UPDATE game_event SET description='Die Schlacht um die Sonnenweiten Phase Monument' WHERE entry=312;
UPDATE game_event SET description='Die Schlacht um die Sonnenweiten Phase Kein Alchemielabor' WHERE entry=313;
UPDATE game_event SET description='Die Schlacht um die Sonnenweiten Phase Alchemielabor' WHERE entry=314;
UPDATE game_event SET description='Die Schlacht um die Sonnenweiten Phase Kiru' WHERE entry=315;
UPDATE game_event SET description='Der Sonnenbrunnen - Alle Tore geschlossen' WHERE entry=316;
UPDATE game_event SET description='Der Sonnenbrunnen - Erstes Tor geöffnet' WHERE entry=317;
UPDATE game_event SET description='Der Sonnenbrunnen - Zweites Tor geöffnet' WHERE entry=318;
UPDATE game_event SET description='Der Sonnenbrunnen - Alle Tore geöffnet' WHERE entry=319;
UPDATE game_event SET description='Shattrath - Tägliche Dungeonquest - Gesucht: Schildwachen der Arkatraz' WHERE entry=1000;
UPDATE game_event SET description='Shattrath - Tägliche Dungeonquest - Gesucht: Myrmidonen des Echsenkessels' WHERE entry=1001;
UPDATE game_event SET description='Shattrath - Tägliche Dungeonquest - Gesucht: Bösartige Ausbilderinnen' WHERE entry=1002;
UPDATE game_event SET description='Shattrath - Tägliche Dungeonquest - Gesucht: Fürsten der Zeitenrisse' WHERE entry=1003;
UPDATE game_event SET description='Shattrath - Tägliche Dungeonquest - Gesucht: Zenturionen der Zerschmetterten Hand' WHERE entry=1004;
UPDATE game_event SET description='Shattrath - Tägliche Dungeonquest - Gesucht: Kanalisierer der Sonnensucher' WHERE entry=1005;
UPDATE game_event SET description='Shattrath - Tägliche Dungeonquest - Gesucht: Zerstörer der Sturmschmiede' WHERE entry=1006;
UPDATE game_event SET description='Shattrath - Tägliche Dungeonquest - Gesucht: Schwestern der Qual' WHERE entry=1007;
UPDATE game_event SET description='Shattrath - Tägliche Heroische Dungeonquest - Gesucht: Nazans Reitgerte' WHERE entry=1008;
UPDATE game_event SET description='Shattrath - Tägliche Heroische Dungeonquest - Gesucht: Ei der Schattenmutter' WHERE entry=1009;
UPDATE game_event SET description='Shattrath - Tägliche Heroische Dungeonquest - Gesucht: Warpzweigsplitter' WHERE entry=1010;
UPDATE game_event SET description='Shattrath - Tägliche Heroische Dungeonquest - Gesucht: Aeonus\' Stundenglas' WHERE entry=1011;
UPDATE game_event SET description='Shattrath - Tägliche Heroische Dungeonquest - Gesucht: Messerfausts Siegel' WHERE entry=1012;
UPDATE game_event SET description='Shattrath - Tägliche Heroische Dungeonquest - Gesucht: Keli\'dans gefiederter Stab' WHERE entry=1013;
UPDATE game_event SET description='Shattrath - Tägliche Heroische Dungeonquest - Gesucht: Murmurs Flüstern' WHERE entry=1014;
UPDATE game_event SET description='Shattrath - Tägliche Heroische Dungeonquest - Gesucht: Pathaleons Projektionsgerät' WHERE entry=1015;
UPDATE game_event SET description='Shattrath - Tägliche Heroische Dungeonquest - Gesucht: Shaffars wundersames Amulett' WHERE entry=1016;
UPDATE game_event SET description='Shattrath - Tägliche Heroische Dungeonquest - Gesucht: Der Kopf des Epochenjägers' WHERE entry=1017;
UPDATE game_event SET description='Shattrath - Tägliche Heroische Dungeonquest - Gesucht: Der Seelenedelstein des Exarchen' WHERE entry=1018;
UPDATE game_event SET description='Shattrath - Tägliche Heroische Dungeonquest - Gesucht: Die Kopfschmuckfedern von Ikiss' WHERE entry=1019;
UPDATE game_event SET description='Shattrath - Tägliche Heroische Dungeonquest - Gesucht: Das Herz von Quagmirran' WHERE entry=1020;
UPDATE game_event SET description='Shattrath - Tägliche Heroische Dungeonquest - Gesucht: Horizontiss\' Schriftrolle' WHERE entry=1021;
UPDATE game_event SET description='Shattrath - Tägliche Heroische Dungeonquest - Gesucht: Die Aufzeichnungen des Kriegsherren' WHERE entry=1022;
UPDATE game_event SET description='Shattrath - Tägliche Heroische Dungeonquest - Gesucht: Gesucht: Der Siegelring von Prinz Kael\'thas' WHERE entry=1023;
UPDATE game_event SET description='Glockenläuten zur vollen Stunde' WHERE entry=1024;
UPDATE game_event SET description='Dalaran - Zufälliger wöchentlicher Schlachtzug - Anub\'Rekhan muss sterben!' WHERE entry=1100;
UPDATE game_event SET description='Dalaran - Zufälliger wöchentlicher Schlachtzug - Der Flammenleviathan muss sterben!' WHERE entry=1101;
UPDATE game_event SET description='Dalaran - Zufälliger wöchentlicher Schlachtzug - Ignis, Meister des Eisenwerks, muss sterben!' WHERE entry=1102;
UPDATE game_event SET description='Dalaran - Zufälliger wöchentlicher Schlachtzug - Instrukteur Razuvious muss sterben!' WHERE entry=1103;
UPDATE game_event SET description='Dalaran - Zufälliger wöchentlicher Schlachtzug - Lord Jaraxxus muss sterben!' WHERE entry=1104;
UPDATE game_event SET description='Dalaran - Zufälliger wöchentlicher Schlachtzug - Lord Mark\'gar muss sterben!' WHERE entry=1105;
UPDATE game_event SET description='Dalaran - Zufälliger wöchentlicher Schlachtzug - Malygos muss sterben!' WHERE entry=1106;
UPDATE game_event SET description='Dalaran - Zufälliger wöchentlicher Schlachtzug - Noth der Seuchenfürst muss sterben!' WHERE entry=1107;
UPDATE game_event SET description='Dalaran - Zufälliger wöchentlicher Schlachtzug - Flickwerk muss sterben!' WHERE entry=1108;
UPDATE game_event SET description='Dalaran - Zufälliger wöchentlicher Schlachtzug - Klingenschuppe muss sterben!' WHERE entry=1109;
UPDATE game_event SET description='Dalaran - Zufälliger wöchentlicher Schlachtzug - Sartharion muss sterben!' WHERE entry=1110;
UPDATE game_event SET description='Dalaran - Zufälliger wöchentlicher Schlachtzug - XT-002 Dekonstruktor muss sterben!' WHERE entry=1111;
UPDATE game_event SET description='Liebe liegt in der Luft - Zufällige tägliche Quest - Ein perfekter Hauch von Parfüm' WHERE entry=1112;
UPDATE game_event SET description='Liebe liegt in der Luft - Zufällige tägliche Quest - Ein feines Duftwasserwölkchen' WHERE entry=1113;
UPDATE game_event SET description='Liebe liegt in der Luft - Zufällige tägliche Quest - Bonbonangriff' WHERE entry=1114;
UPDATE game_event SET description='Eiskrone - Turnier - Zufällige tägliche Quest - Drottinn Hrothgar' WHERE entry=1115;
UPDATE game_event SET description='Eiskrone - Turnier - Zufällige tägliche Quest - Nebelrufer Yngvar' WHERE entry=1116;
UPDATE game_event SET description='Eiskrone - Turnier - Zufällige tägliche Quest - Ornolf der Vernarbte' WHERE entry=1117;
UPDATE game_event SET description='Eiskrone - Turnier - Zufällige tägliche Quest - Todessprecher Kharos' WHERE entry=1118;
UPDATE game_event SET description='Der Krater von Un\'Goro (1) - Zufällige tägliche Quest - Sooooo hungrig' WHERE entry=1119;
UPDATE game_event SET description='Der Krater von Un\'Goro (1) - Zufällige tägliche Quest - Gorishigelee' WHERE entry=1120;
UPDATE game_event SET description='Der Krater von Un\'Goro (1) - Zufällige tägliche Quest - Pochiert, gerührt oder roh?' WHERE entry=1121;
UPDATE game_event SET description='Der Krater von Un\'Goro (1) - Zufällige tägliche Quest - Sengende Rocfedern' WHERE entry=1122;
UPDATE game_event SET description='Der Krater von Un\'Goro (2) - Zufällige tägliche Quest - Sooooo hungrig' WHERE entry=1123;
UPDATE game_event SET description='Der Krater von Un\'Goro (2) - Zufällige tägliche Quest - Gorishigelee' WHERE entry=1124;
UPDATE game_event SET description='Der Krater von Un\'Goro (2) - Zufällige tägliche Quest - Pochiert, gerührt oder roh?' WHERE entry=1125;
UPDATE game_event SET description='Der Krater von Un\'Goro (2) - Zufällige tägliche Quest - Sengende Rocfedern' WHERE entry=1126;
UPDATE game_event SET description='Shattrath - Zufällige tägliche Kochquest - Rache ist süß' WHERE entry=1127;
UPDATE game_event SET description='Shattrath - Zufällige tägliche Kochquest - Superheißes Ragout' WHERE entry=1128;
UPDATE game_event SET description='Shattrath - Zufällige tägliche Kochquest - Manaziös' WHERE entry=1129;
UPDATE game_event SET description='Shattrath - Zufällige tägliche Kochquest - Suppe für die Seele' WHERE entry=1130;
UPDATE game_event SET description='Wälder von Terokkar - Der alte Barlo - Zufällige tägliche Angelquest - Krokilisken in der Stadt' WHERE entry=1131;
UPDATE game_event SET description='Wälder von Terokkar - Der alte Barlo - Zufällige tägliche Angelquest - Köderbanditen' WHERE entry=1132;
UPDATE game_event SET description='Wälder von Terokkar - Der alte Barlo - Zufällige tägliche Angelquest - Der Eine, der entkam' WHERE entry=1133;
UPDATE game_event SET description='Wälder von Terokkar - Der alte Barlo - Zufällige tägliche Angelquest - Garnelenfangen ist nicht einfach' WHERE entry=1134;
UPDATE game_event SET description='Wälder von Terokkar - Der alte Barlo - Zufällige tägliche Angelquest - Teufelsblutfilet' WHERE entry=1135;
UPDATE game_event SET description='Die Sturmgipfel - Gretta die Schiedsfrau - Zufällige tägliche Quest - Zurück in die Grube' WHERE entry=1136;
UPDATE game_event SET description='Die Sturmgipfel - Gretta die Schiedsfrau - Zufällige tägliche Quest - Euren Titel verteidigen' WHERE entry=1137;
UPDATE game_event SET description='Die Sturmgipfel - Gretta die Schiedsfrau - Zufällige tägliche Quest - Disziplin bewahren' WHERE entry=1138;
UPDATE game_event SET description='Die Sturmgipfel - Gretta die Schiedsfrau - Zufällige tägliche Quest - Die Missgeburten müssen sterben' WHERE entry=1139;
UPDATE game_event SET description='Sholazarbecken - Orakel Soo-dau - Zufällige tägliche Quest - Beherrschen der Kristalle' WHERE entry=1140;
UPDATE game_event SET description='Sholazarbecken - Orakel Soo-dau - Zufällige tägliche Quest - Macht der Großen' WHERE entry=1141;
UPDATE game_event SET description='Sholazarbecken - Orakel Soo-dau - Zufällige tägliche Quest - Wille der Titanen' WHERE entry=1142;
UPDATE game_event SET description='Sholazarbecken - Rejek - Zufällige tägliche Quest - Des Helden Helm' WHERE entry=1143;
UPDATE game_event SET description='Sholazarbecken - Rejek - Zufällige tägliche Quest - Rejek: Erstes Blut' WHERE entry=1144;
UPDATE game_event SET description='Sholazarbecken - Rejek - Zufällige tägliche Quest - Die Stärke des Sturms' WHERE entry=1145;
UPDATE game_event SET description='Sholazarbecken - Rejek - Zufällige tägliche Quest - Des Herzbluts Stärke' WHERE entry=1146;
UPDATE game_event SET description='Sholazarbecken - Vekgar - Zufällige tägliche Quest - Kartaks Wut' WHERE entry=1147;
UPDATE game_event SET description='Sholazarbecken - Vekgar - Zufällige tägliche Quest - Geheime Kraft der Wildherzen' WHERE entry=1148;
UPDATE game_event SET description='Sholazarbecken - Vekgar - Zufällige tägliche Quest - Instrument des Krieges' WHERE entry=1149;
UPDATE game_event SET description='Eiskrone - Turnier (1) - Zufällige tägliche Quest - Legt mal ein Bein zu' WHERE entry=1150;
UPDATE game_event SET description='Eiskrone - Turnier (1) - Zufällige tägliche Quest - Rettungseinsatz auf See' WHERE entry=1151;
UPDATE game_event SET description='Eiskrone - Turnier (1) - Zufällige tägliche Quest - Einhalt den Aggressoren' WHERE entry=1152;
UPDATE game_event SET description='Eiskrone - Turnier (1) - Zufällige tägliche Quest - Die Barmherzigkeit des Lichts' WHERE entry=1153;
UPDATE game_event SET description='Eiskrone - Turnier (2) - Zufällige tägliche Quest - Frühstück der Champions' WHERE entry=1154;
UPDATE game_event SET description='Eiskrone - Turnier (2) - Zufällige tägliche Quest - Gormok will seine Schneebolde' WHERE entry=1155;
UPDATE game_event SET description='Eiskrone - Turnier (2) - Zufällige tägliche Quest - Was fressen eigentlich Yetis?' WHERE entry=1156;
UPDATE game_event SET description='Eiskrone - Turnier (3) - Zufällige tägliche Quest - Legt mal ein Bein zu' WHERE entry=1157;
UPDATE game_event SET description='Eiskrone - Turnier (3) - Zufällige tägliche Quest - Rettungseinsatz auf See' WHERE entry=1158;
UPDATE game_event SET description='Eiskrone - Turnier (3) - Zufällige tägliche Quest - Einhalt den Aggressoren' WHERE entry=1159;
UPDATE game_event SET description='Eiskrone - Turnier (3) - Zufällige tägliche Quest - Die Barmherzigkeit des Lichts' WHERE entry=1160;
UPDATE game_event SET description='Eiskrone - Turnier (4) - Zufällige tägliche Quest - Frühstück der Champions' WHERE entry=1161;
UPDATE game_event SET description='Eiskrone - Turnier (4) - Zufällige tägliche Quest - Gormok will seine Schneebolde' WHERE entry=1162;
UPDATE game_event SET description='Eiskrone - Turnier (4) - Zufällige tägliche Quest - Was fressen eigentlich Yetis?' WHERE entry=1163;
UPDATE game_event SET description='Sholazarbecken - Orakel Soo-nee - Zufällige tägliche Quest - Ein reinigendes Lied' WHERE entry=1164;
UPDATE game_event SET description='Sholazarbecken - Orakel Soo-nee - Zufällige tägliche Quest - Lied der Fruchtbarkeit' WHERE entry=1165;
UPDATE game_event SET description='Sholazarbecken - Orakel Soo-nee - Zufällige tägliche Quest - Lied der Besinnung' WHERE entry=1166;
UPDATE game_event SET description='Sholazarbecken - Orakel Soo-nee - Zufällige tägliche Quest - Lied von Wind und Wasser' WHERE entry=1167;
UPDATE game_event SET description='Eiskrone - Turnier - Zufällige tägliche Quest - Kraken am Haken' WHERE entry=1168;
UPDATE game_event SET description='Eiskrone - Turnier - Zufällige tägliche Quest - Das Schicksal der Gefallenen' WHERE entry=1169;
UPDATE game_event SET description='Zul\'Drak - Kommandant Kunz - Zufällige tägliche Quest - Trollpatrouille 1' WHERE entry=1170;
UPDATE game_event SET description='Zul\'Drak - Kommandant Kunz - Zufällige tägliche Quest - Trollpatrouille 2' WHERE entry=1171;
UPDATE game_event SET description='Zul\'Drak - Kommandant Kunz - Zufällige tägliche Quest - Trollpatrouille 3' WHERE entry=1172;
UPDATE game_event SET description='Dalaran - Zufällige tägliche Kochquest (Allianz) - Energieerfüllter Pilzhackbraten' WHERE entry=1173;
UPDATE game_event SET description='Dalaran - Zufällige tägliche Kochquest (Allianz) - Versammlung im Zauberkasten' WHERE entry=1174;
UPDATE game_event SET description='Dalaran - Zufällige tägliche Kochquest (Allianz) - Kanaleintopf' WHERE entry=1175;
UPDATE game_event SET description='Dalaran - Zufällige tägliche Kochquest (Allianz) - Käse für Leuchtegold' WHERE entry=1176;
UPDATE game_event SET description='Dalaran - Zufällige tägliche Kochquest (Allianz) - Senfwürstchen!' WHERE entry=1177;
UPDATE game_event SET description='Dalaran - Zufällige tägliche Kochquest (Horde) - Energieerfüllter Pilzhackbraten' WHERE entry=1178;
UPDATE game_event SET description='Dalaran - Zufällige tägliche Kochquest (Horde) - Versammlung im Zauberkasten' WHERE entry=1179;
UPDATE game_event SET description='Dalaran - Zufällige tägliche Kochquest (Horde) - Kanaleintopf' WHERE entry=1180;
UPDATE game_event SET description='Dalaran - Zufällige tägliche Kochquest (Horde) - Käse für Leuchtegold' WHERE entry=1181;
UPDATE game_event SET description='Dalaran - Zufällige tägliche Kochquest (Horde) - Senfwürstchen!' WHERE entry=1182;
UPDATE game_event SET description='Dalaran - Zufällige tägliche Angelquest - Der Geisterfisch' WHERE entry=1183;
UPDATE game_event SET description='Dalaran - Zufällige tägliche Angelquest - Perle der Kanalisation' WHERE entry=1184;
UPDATE game_event SET description='Dalaran - Zufällige tägliche Angelquest - Blut ist dicker' WHERE entry=1185;
UPDATE game_event SET description='Dalaran - Zufällige tägliche Angelquest - Gefährlich köstlich' WHERE entry=1186;
UPDATE game_event SET description='Dalaran - Zufällige tägliche Angelquest - Arm dran, Arm ab!' WHERE entry=1187;
UPDATE game_event SET description='Dalaran - Zufällige tägliche Juwelierskunstquest - Lieferung: Blutrotes Nephritamulett' WHERE entry=1188;
UPDATE game_event SET description='Dalaran - Zufällige tägliche Juwelierskunstquest - Lieferung: Helles Rüstungsrelikt' WHERE entry=1189;
UPDATE game_event SET description='Dalaran - Zufällige tägliche Juwelierskunstquest - Lieferung: Leuchtende Elfenbeinfigur' WHERE entry=1190;
UPDATE game_event SET description='Dalaran - Zufällige tägliche Juwelierskunstquest - Lieferung: Aufwändige Knochenfigur' WHERE entry=1191;
UPDATE game_event SET description='Dalaran - Zufällige tägliche Juwelierskunstquest - Lieferung: Unbeständige Sonnenkuriosität' WHERE entry=1192;
UPDATE game_event SET description='Dalaran - Zufällige tägliche Juwelierskunstquest - Lieferung: Tückische Sonnenbrosche' WHERE entry=1193;
UPDATE game_event SET description='Tausendwinter - Zufällige wöchentliche PvP-Quest (Allianz 1) - Ein seltenes Kraut' WHERE entry=1194;
UPDATE game_event SET description='Tausendwinter - Zufällige wöchentliche PvP-Quest (Allianz 1) - Pfeil und Knochen' WHERE entry=1195;
UPDATE game_event SET description='Tausendwinter - Zufällige wöchentliche PvP-Quest (Allianz 1) - Verwüster auftanken' WHERE entry=1196;
UPDATE game_event SET description='Tausendwinter - Zufällige wöchentliche PvP-Quest (Allianz 1) - Die Krieger schützen' WHERE entry=1197;
UPDATE game_event SET description='Tausendwinter - Zufällige wöchentliche PvP-Quest (Allianz 2) - Ein seltenes Kraut' WHERE entry=1198;
UPDATE game_event SET description='Tausendwinter - Zufällige wöchentliche PvP-Quest (Allianz 2) - Pfeil und Knochen' WHERE entry=1199;
UPDATE game_event SET description='Tausendwinter - Zufällige wöchentliche PvP-Quest (Allianz 2) - Verwüster auftanken' WHERE entry=1200;
UPDATE game_event SET description='Tausendwinter - Zufällige wöchentliche PvP-Quest (Allianz 2) - Die Krieger schützen' WHERE entry=1201;
UPDATE game_event SET description='Tausendwinter - Zufällige wöchentliche PvP-Quest (Horde 1) - Ein seltenes Kraut' WHERE entry=1202;
UPDATE game_event SET description='Tausendwinter - Zufällige wöchentliche PvP-Quest (Horde 1) - Pfeil und Knochen' WHERE entry=1203;
UPDATE game_event SET description='Tausendwinter - Zufällige wöchentliche PvP-Quest (Horde 1) - Verwüster auftanken' WHERE entry=1204;
UPDATE game_event SET description='Tausendwinter - Zufällige wöchentliche PvP-Quest (Horde 1) - Die Mauern verhexen' WHERE entry=1205;
UPDATE game_event SET description='Tausendwinter - Zufällige wöchentliche PvP-Quest (Horde 2) - Mit Rosen heilen' WHERE entry=1206;
UPDATE game_event SET description='Tausendwinter - Zufällige wöchentliche PvP-Quest (Horde 2) - Pfeil und Knochen' WHERE entry=1207;
UPDATE game_event SET description='Tausendwinter - Zufällige wöchentliche PvP-Quest (Horde 2) - Verwüster auftanken' WHERE entry=1208;
UPDATE game_event SET description='Tausendwinter - Zufällige wöchentliche PvP-Quest (Horde 2) - Die Wälle schützen' WHERE entry=1209;
UPDATE game_event SET description='Eiskrone - Turnier (Die Sonnenhäscher) - Zufällige tägliche Quest - Eine Klinge, eines Champions würdig' WHERE entry=1210;
UPDATE game_event SET description='Eiskrone - Turnier (Die Sonnenhäscher) - Zufällige tägliche Quest - Eine würdige Waffe' WHERE entry=1211;
UPDATE game_event SET description='Eiskrone - Turnier (Die Sonnenhäscher) - Zufällige tägliche Quest - Auf Winters Schneide' WHERE entry=1212;
UPDATE game_event SET description='Eiskrone - Turnier (Orcs) - Zufällige tägliche Quest - Eine Klinge, eines Champions würdig' WHERE entry=1213;
UPDATE game_event SET description='Eiskrone - Turnier (Orcs) - Zufällige tägliche Quest - Eine würdige Waffe' WHERE entry=1214;
UPDATE game_event SET description='Eiskrone - Turnier (Orcs) - Zufällige tägliche Quest - Auf Winters Schneide' WHERE entry=1215;
UPDATE game_event SET description='Eiskrone - Turnier (Trolle) - Zufällige tägliche Quest - Eine Klinge, eines Champions würdig' WHERE entry=1216;
UPDATE game_event SET description='Eiskrone - Turnier (Trolle) - Zufällige tägliche Quest - Eine würdige Waffe' WHERE entry=1217;
UPDATE game_event SET description='Eiskrone - Turnier (Trolle) - Zufällige tägliche Quest - Auf Winters Schneide' WHERE entry=1218;
UPDATE game_event SET description='Eiskrone - Turnier (Tauren) - Zufällige tägliche Quest - Eine Klinge, eines Champions würdig' WHERE entry=1219;
UPDATE game_event SET description='Eiskrone - Turnier (Tauren) - Zufällige tägliche Quest - Eine würdige Waffe' WHERE entry=1220;
UPDATE game_event SET description='Eiskrone - Turnier (Tauren) - Zufällige tägliche Quest - Auf Winters Schneide' WHERE entry=1221;
UPDATE game_event SET description='Eiskrone - Turnier (Verlassene) - Zufällige tägliche Quest - Eine Klinge, eines Champions würdig' WHERE entry=1222;
UPDATE game_event SET description='Eiskrone - Turnier (Verlassene) - Zufällige tägliche Quest - Eine würdige Waffe' WHERE entry=1223;
UPDATE game_event SET description='Eiskrone - Turnier (Verlassene) - Zufällige tägliche Quest - Auf Winters Schneide' WHERE entry=1224;
UPDATE game_event SET description='Eiskrone - Turnier (Blutelfen) - Zufällige tägliche Quest - Eine Klinge, eines Champions würdig' WHERE entry=1225;
UPDATE game_event SET description='Eiskrone - Turnier (Blutelfen) - Zufällige tägliche Quest - Eine würdige Waffe' WHERE entry=1226;
UPDATE game_event SET description='Eiskrone - Turnier (Blutelfen) - Zufällige tägliche Quest - Auf Winters Schneide' WHERE entry=1227;
UPDATE game_event SET description='Eiskrone - Turnier (Der Silberbund) - Zufällige tägliche Quest - Eine Klinge, eines Champions würdig' WHERE entry=1228;
UPDATE game_event SET description='Eiskrone - Turnier (Der Silberbund) - Zufällige tägliche Quest - Eine würdige Waffe' WHERE entry=1229;
UPDATE game_event SET description='Eiskrone - Turnier (Der Silberbund) - Zufällige tägliche Quest - Auf Winters Schneide' WHERE entry=1230;
UPDATE game_event SET description='Eiskrone - Turnier (Menschen) - Zufällige tägliche Quest - Eine Klinge, eines Champions würdig' WHERE entry=1231;
UPDATE game_event SET description='Eiskrone - Turnier (Menschen) - Zufällige tägliche Quest - Eine würdige Waffe' WHERE entry=1232;
UPDATE game_event SET description='Eiskrone - Turnier (Menschen) - Zufällige tägliche Quest - Auf Winters Schneide' WHERE entry=1233;
UPDATE game_event SET description='Eiskrone - Turnier (Zwerge) - Zufällige tägliche Quest - Eine Klinge, eines Champions würdig' WHERE entry=1234;
UPDATE game_event SET description='Eiskrone - Turnier (Zwerge) - Zufällige tägliche Quest - Eine würdige Waffe' WHERE entry=1235;
UPDATE game_event SET description='Eiskrone - Turnier (Zwerge) - Zufällige tägliche Quest - Auf Winters Schneide' WHERE entry=1236;
UPDATE game_event SET description='Eiskrone - Turnier (Gnome) - Zufällige tägliche Quest - Eine Klinge, eines Champions würdig' WHERE entry=1237;
UPDATE game_event SET description='Eiskrone - Turnier (Gnome) - Zufällige tägliche Quest - Eine würdige Waffe' WHERE entry=1238;
UPDATE game_event SET description='Eiskrone - Turnier (Gnome) - Zufällige tägliche Quest - Auf Winters Schneide' WHERE entry=1239;
UPDATE game_event SET description='Eiskrone - Turnier (Nachtelfen) - Zufällige tägliche Quest - Eine Klinge, eines Champions würdig' WHERE entry=1240;
UPDATE game_event SET description='Eiskrone - Turnier (Nachtelfen) - Zufällige tägliche Quest - Eine würdige Waffe' WHERE entry=1241;
UPDATE game_event SET description='Eiskrone - Turnier (Nachtelfen) - Zufällige tägliche Quest - Auf Winters Schneide' WHERE entry=1242;
UPDATE game_event SET description='Eiskrone - Turnier (Draenei) - Zufällige tägliche Quest - Eine Klinge, eines Champions würdig' WHERE entry=1243;
UPDATE game_event SET description='Eiskrone - Turnier (Draenei) - Zufällige tägliche Quest - Eine würdige Waffe' WHERE entry=1244;
UPDATE game_event SET description='Eiskrone - Turnier (Draenei) - Zufällige tägliche Quest - Auf Winters Schneide' WHERE entry=1245;
SET NAMES 'latin1';
