#####  instance_dungeon_encounters  #####

-- UPDATE instance_dungeon_encounters SET EncounterName2=NULL , EncounterName3=NULL , EncounterName4=NULL , EncounterName5=NULL , EncounterName6=NULL , EncounterName7=NULL , EncounterName8=NULL , EncounterName9=NULL , EncounterName10=NULL , EncounterName11=NULL , EncounterName12=NULL , EncounterName13=NULL , EncounterName14=NULL , EncounterName15=NULL , EncounterName16=NULL;
UPDATE instance_dungeon_encounters SET EncounterName4=NULL;
ALTER TABLE instance_dungeon_encounters ORDER BY Id ASC;

SET NAMES 'utf8';
UPDATE instance_dungeon_encounters SET EncounterName4='Rhahk\'zor' WHERE Id=161;
UPDATE instance_dungeon_encounters SET EncounterName4='Sneed' WHERE Id=162;
UPDATE instance_dungeon_encounters SET EncounterName4='Gilnid' WHERE Id=163;
UPDATE instance_dungeon_encounters SET EncounterName4='Handlanger Pein' WHERE Id=164;
UPDATE instance_dungeon_encounters SET EncounterName4='Krümel' WHERE Id=165;
UPDATE instance_dungeon_encounters SET EncounterName4='Kapitän Grünhaut' WHERE Id=166;
UPDATE instance_dungeon_encounters SET EncounterName4='Edwin VanCleef' WHERE Id=167;

UPDATE instance_dungeon_encounters SET EncounterName4='Shirrak der Totenwächter' WHERE Id=201;
UPDATE instance_dungeon_encounters SET EncounterName4='Exarch Maladaar' WHERE Id=202;
UPDATE instance_dungeon_encounters SET EncounterName4='Pandemonius' WHERE Id=203;
UPDATE instance_dungeon_encounters SET EncounterName4='Tavarok' WHERE Id=204;
UPDATE instance_dungeon_encounters SET EncounterName4='Nexusprinz Shaffar' WHERE Id=205;
UPDATE instance_dungeon_encounters SET EncounterName4='Dunkelwirker Syth' WHERE Id=206;
UPDATE instance_dungeon_encounters SET EncounterName4='Klauenkönig Ikiss' WHERE Id=207;
UPDATE instance_dungeon_encounters SET EncounterName4='Botschafter Höllenschlund' WHERE Id=208;
UPDATE instance_dungeon_encounters SET EncounterName4='Schwarzherz der Hetzer' WHERE Id=209;
UPDATE instance_dungeon_encounters SET EncounterName4='Großmeister Vorpil' WHERE Id=210;
UPDATE instance_dungeon_encounters SET EncounterName4='Murmur' WHERE Id=211;
UPDATE instance_dungeon_encounters SET EncounterName4='Urahne Nadox' WHERE Id=212;
UPDATE instance_dungeon_encounters SET EncounterName4='Prinz Taldaram' WHERE Id=213;
UPDATE instance_dungeon_encounters SET EncounterName4='Jedoga Schattensucher' WHERE Id=214;
UPDATE instance_dungeon_encounters SET EncounterName4='Herold Volazj' WHERE Id=215;
UPDATE instance_dungeon_encounters SET EncounterName4='Krik\'thir der Torwächter' WHERE Id=216;
UPDATE instance_dungeon_encounters SET EncounterName4='Hadronox' WHERE Id=217;
UPDATE instance_dungeon_encounters SET EncounterName4='Anub\'arak' WHERE Id=218;
UPDATE instance_dungeon_encounters SET EncounterName4='Ghamoo-ra' WHERE Id=219;
UPDATE instance_dungeon_encounters SET EncounterName4='Lady Sarevess' WHERE Id=220;
UPDATE instance_dungeon_encounters SET EncounterName4='Gelihast' WHERE Id=221;
UPDATE instance_dungeon_encounters SET EncounterName4='Lorgus Jett' WHERE Id=222;
UPDATE instance_dungeon_encounters SET EncounterName4='Alter Serra\'kis' WHERE Id=224;
UPDATE instance_dungeon_encounters SET EncounterName4='Kelris, Lord des Schattenhammers' WHERE Id=225;
UPDATE instance_dungeon_encounters SET EncounterName4='Aku\'mai' WHERE Id=226;
UPDATE instance_dungeon_encounters SET EncounterName4='Verhörmeisterin Gerstahn' WHERE Id=227;
UPDATE instance_dungeon_encounters SET EncounterName4='Lord Roccor' WHERE Id=228;
UPDATE instance_dungeon_encounters SET EncounterName4='Hundemeister Grebmar' WHERE Id=229;
UPDATE instance_dungeon_encounters SET EncounterName4='Ring des Gesetzes' WHERE Id=230;
UPDATE instance_dungeon_encounters SET EncounterName4='Pyromant Weisenkorn' WHERE Id=231;
UPDATE instance_dungeon_encounters SET EncounterName4='Lord Incendius' WHERE Id=232;
UPDATE instance_dungeon_encounters SET EncounterName4='Wärter Stilgiss' WHERE Id=233;
UPDATE instance_dungeon_encounters SET EncounterName4='Fineous Dunkelader' WHERE Id=234;
UPDATE instance_dungeon_encounters SET EncounterName4='Bael\'Gar' WHERE Id=235;
UPDATE instance_dungeon_encounters SET EncounterName4='General Zornesschmied' WHERE Id=236;
UPDATE instance_dungeon_encounters SET EncounterName4='Golemlord Argelmach' WHERE Id=237;
UPDATE instance_dungeon_encounters SET EncounterName4='Hurley Pestatem' WHERE Id=238;
UPDATE instance_dungeon_encounters SET EncounterName4='Phalanx' WHERE Id=239;
UPDATE instance_dungeon_encounters SET EncounterName4='Ribbly Schraubstutz' WHERE Id=240;
UPDATE instance_dungeon_encounters SET EncounterName4='Stöpsel Zapfring' WHERE Id=241;
UPDATE instance_dungeon_encounters SET EncounterName4='Botschafter Flammenschlag' WHERE Id=242;
UPDATE instance_dungeon_encounters SET EncounterName4='Die Sieben' WHERE Id=243;
UPDATE instance_dungeon_encounters SET EncounterName4='Magmus' WHERE Id=244;
UPDATE instance_dungeon_encounters SET EncounterName4='Imperator Dagran Thaurissan' WHERE Id=245;
UPDATE instance_dungeon_encounters SET EncounterName4='Shirrak der Totenwächter' WHERE Id=246;
UPDATE instance_dungeon_encounters SET EncounterName4='Exarch Maladaar' WHERE Id=247;
UPDATE instance_dungeon_encounters SET EncounterName4='Pandemonius' WHERE Id=248;
UPDATE instance_dungeon_encounters SET EncounterName4='Tavarok' WHERE Id=249;
UPDATE instance_dungeon_encounters SET EncounterName4='Yor' WHERE Id=250;
UPDATE instance_dungeon_encounters SET EncounterName4='Nexusprinz Shaffar' WHERE Id=251;
UPDATE instance_dungeon_encounters SET EncounterName4='Dunkelwirker Syth' WHERE Id=252;
UPDATE instance_dungeon_encounters SET EncounterName4='Anzu' WHERE Id=253;
UPDATE instance_dungeon_encounters SET EncounterName4='Klauenkönig Ikiss' WHERE Id=254;
UPDATE instance_dungeon_encounters SET EncounterName4='Botschafter Höllenschlund' WHERE Id=255;
UPDATE instance_dungeon_encounters SET EncounterName4='Schwarzherz der Hetzer' WHERE Id=256;
UPDATE instance_dungeon_encounters SET EncounterName4='Großmeister Vorpil' WHERE Id=257;
UPDATE instance_dungeon_encounters SET EncounterName4='Murmur' WHERE Id=258;
UPDATE instance_dungeon_encounters SET EncounterName4='Urahne Nadox' WHERE Id=259;
UPDATE instance_dungeon_encounters SET EncounterName4='Prinz Taldaram' WHERE Id=260;
UPDATE instance_dungeon_encounters SET EncounterName4='Jedoga Schattensucher' WHERE Id=261;
UPDATE instance_dungeon_encounters SET EncounterName4='Amanitar' WHERE Id=262;
UPDATE instance_dungeon_encounters SET EncounterName4='Herold Volazj' WHERE Id=263;
UPDATE instance_dungeon_encounters SET EncounterName4='Krik\'thir der Torwächter' WHERE Id=264;
UPDATE instance_dungeon_encounters SET EncounterName4='Hadronox' WHERE Id=265;
UPDATE instance_dungeon_encounters SET EncounterName4='Anub\'arak' WHERE Id=266;
UPDATE instance_dungeon_encounters SET EncounterName4='Hochlord Omokk' WHERE Id=267;
UPDATE instance_dungeon_encounters SET EncounterName4='Schattenjägerin Vosh\'gajin' WHERE Id=268;
UPDATE instance_dungeon_encounters SET EncounterName4='Kriegsmeister Voone' WHERE Id=269;
UPDATE instance_dungeon_encounters SET EncounterName4='Mutter Glimmernetz' WHERE Id=270;
UPDATE instance_dungeon_encounters SET EncounterName4='Urok Schreckensbote' WHERE Id=271;
UPDATE instance_dungeon_encounters SET EncounterName4='Rüstmeister Zigris' WHERE Id=272;
UPDATE instance_dungeon_encounters SET EncounterName4='Gizrul der Geifernde' WHERE Id=273;
UPDATE instance_dungeon_encounters SET EncounterName4='Halycon' WHERE Id=274;
UPDATE instance_dungeon_encounters SET EncounterName4='Oberanführer Wyrmthalak' WHERE Id=275;
UPDATE instance_dungeon_encounters SET EncounterName4='Feuerwache Glutseher' WHERE Id=276;
UPDATE instance_dungeon_encounters SET EncounterName4='Solakar Feuerkrone' WHERE Id=277;
UPDATE instance_dungeon_encounters SET EncounterName4='Kriegshäuptling Rend Schwarzfaust' WHERE Id=278;
UPDATE instance_dungeon_encounters SET EncounterName4='Die Bestie' WHERE Id=279;
UPDATE instance_dungeon_encounters SET EncounterName4='General Drakkisath' WHERE Id=280;
UPDATE instance_dungeon_encounters SET EncounterName4='Epochenjäger' WHERE Id=281;
UPDATE instance_dungeon_encounters SET EncounterName4='Epochenjäger' WHERE Id=282;
UPDATE instance_dungeon_encounters SET EncounterName4='Hauptmann Skarloc' WHERE Id=283;
UPDATE instance_dungeon_encounters SET EncounterName4='Hauptmann Skarloc' WHERE Id=284;
UPDATE instance_dungeon_encounters SET EncounterName4='Leutnant Drach' WHERE Id=285;
UPDATE instance_dungeon_encounters SET EncounterName4='Leutnant Drach' WHERE Id=286;
UPDATE instance_dungeon_encounters SET EncounterName4='Chronolord Deja' WHERE Id=287;
UPDATE instance_dungeon_encounters SET EncounterName4='Chronolord Deja' WHERE Id=288;
UPDATE instance_dungeon_encounters SET EncounterName4='Temporus' WHERE Id=289;
UPDATE instance_dungeon_encounters SET EncounterName4='Temporus' WHERE Id=290;
UPDATE instance_dungeon_encounters SET EncounterName4='Aeonus' WHERE Id=291;
UPDATE instance_dungeon_encounters SET EncounterName4='Aeonus' WHERE Id=292;
UPDATE instance_dungeon_encounters SET EncounterName4='Fleischhaken' WHERE Id=293;
UPDATE instance_dungeon_encounters SET EncounterName4='Salramm der Fleischformer' WHERE Id=294;
UPDATE instance_dungeon_encounters SET EncounterName4='Chronolord Epoch' WHERE Id=295;
UPDATE instance_dungeon_encounters SET EncounterName4='Mal\'Ganis' WHERE Id=296;
UPDATE instance_dungeon_encounters SET EncounterName4='Fleischhaken' WHERE Id=297;
UPDATE instance_dungeon_encounters SET EncounterName4='Salramm der Fleischformer' WHERE Id=298;
UPDATE instance_dungeon_encounters SET EncounterName4='Chronolord Epoch' WHERE Id=299;
UPDATE instance_dungeon_encounters SET EncounterName4='Mal\'Ganis' WHERE Id=300;
UPDATE instance_dungeon_encounters SET EncounterName4='Mennu der Verräter' WHERE Id=301;
UPDATE instance_dungeon_encounters SET EncounterName4='Rokmar der Zerquetscher' WHERE Id=302;
UPDATE instance_dungeon_encounters SET EncounterName4='Quagmirran' WHERE Id=303;
UPDATE instance_dungeon_encounters SET EncounterName4='Mennu der Verräter' WHERE Id=304;
UPDATE instance_dungeon_encounters SET EncounterName4='Rokmar der Zerquetscher' WHERE Id=305;
UPDATE instance_dungeon_encounters SET EncounterName4='Quagmirran' WHERE Id=306;

UPDATE instance_dungeon_encounters SET EncounterName4='Wasserbeschwörerin Thespia' WHERE Id=314;
UPDATE instance_dungeon_encounters SET EncounterName4='Wasserbeschwörerin Thespia' WHERE Id=315;
UPDATE instance_dungeon_encounters SET EncounterName4='Robogenieur Dampfhammer' WHERE Id=316;
UPDATE instance_dungeon_encounters SET EncounterName4='Robogenieur Dampfhammer' WHERE Id=317;
UPDATE instance_dungeon_encounters SET EncounterName4='Kriegsherr Kalithresh' WHERE Id=318;
UPDATE instance_dungeon_encounters SET EncounterName4='Kriegsherr Kalithresh' WHERE Id=319;
UPDATE instance_dungeon_encounters SET EncounterName4='Hungarfenn' WHERE Id=320;
UPDATE instance_dungeon_encounters SET EncounterName4='Hungarfenn' WHERE Id=321;
UPDATE instance_dungeon_encounters SET EncounterName4='Ghaz\'an' WHERE Id=322;
UPDATE instance_dungeon_encounters SET EncounterName4='Ghaz\'an' WHERE Id=323;

UPDATE instance_dungeon_encounters SET EncounterName4='Sumpffürst Musel\'ek' WHERE Id=329;
UPDATE instance_dungeon_encounters SET EncounterName4='Sumpffürst Musel\'ek' WHERE Id=330;
UPDATE instance_dungeon_encounters SET EncounterName4='Die Schattenmutter' WHERE Id=331;
UPDATE instance_dungeon_encounters SET EncounterName4='Die Schattenmutter' WHERE Id=332;

UPDATE instance_dungeon_encounters SET EncounterName4='Großchampions' WHERE Id=334;

UPDATE instance_dungeon_encounters SET EncounterName4='Großchampions' WHERE Id=336;

UPDATE instance_dungeon_encounters SET EncounterName4='Argentumchampion' WHERE Id=338;
UPDATE instance_dungeon_encounters SET EncounterName4='Argentumchampion' WHERE Id=339;
UPDATE instance_dungeon_encounters SET EncounterName4='Der Schwarze Ritter' WHERE Id=340;
UPDATE instance_dungeon_encounters SET EncounterName4='Der Schwarze Ritter' WHERE Id=341;

UPDATE instance_dungeon_encounters SET EncounterName4='Zevrim Dornhuf' WHERE Id=343;
UPDATE instance_dungeon_encounters SET EncounterName4='Hydrobrut' WHERE Id=344;
UPDATE instance_dungeon_encounters SET EncounterName4='Lethtendris' WHERE Id=345;
UPDATE instance_dungeon_encounters SET EncounterName4='Alzzin der Wildformer' WHERE Id=346;
UPDATE instance_dungeon_encounters SET EncounterName4='Illyanna Rabeneiche' WHERE Id=347;
UPDATE instance_dungeon_encounters SET EncounterName4='Magister Kalendris' WHERE Id=348;
UPDATE instance_dungeon_encounters SET EncounterName4='Immol\'thar' WHERE Id=349;
UPDATE instance_dungeon_encounters SET EncounterName4='Tendris Wucherborke' WHERE Id=350;

UPDATE instance_dungeon_encounters SET EncounterName4='Prinz Tortheldrin' WHERE Id=361;
UPDATE instance_dungeon_encounters SET EncounterName4='Wache Mol\'dar' WHERE Id=362;
UPDATE instance_dungeon_encounters SET EncounterName4='Stampfer Kreeg' WHERE Id=363;
UPDATE instance_dungeon_encounters SET EncounterName4='Wache Fengus' WHERE Id=364;
UPDATE instance_dungeon_encounters SET EncounterName4='Wache Slip\'kik' WHERE Id=365;
UPDATE instance_dungeon_encounters SET EncounterName4='Hauptmann Krombruch' WHERE Id=366;
UPDATE instance_dungeon_encounters SET EncounterName4='Cho\'Rush der Beobachter' WHERE Id=367;
UPDATE instance_dungeon_encounters SET EncounterName4='König Gordok' WHERE Id=368;
UPDATE instance_dungeon_encounters SET EncounterName4='Trollgrind' WHERE Id=369;
UPDATE instance_dungeon_encounters SET EncounterName4='Trollgrind' WHERE Id=370;
UPDATE instance_dungeon_encounters SET EncounterName4='Novos der Beschwörer' WHERE Id=371;
UPDATE instance_dungeon_encounters SET EncounterName4='Novos der Beschwörer' WHERE Id=372;
UPDATE instance_dungeon_encounters SET EncounterName4='König Dred' WHERE Id=373;
UPDATE instance_dungeon_encounters SET EncounterName4='König Dred' WHERE Id=374;
UPDATE instance_dungeon_encounters SET EncounterName4='Der Prophet Tharon\'ja' WHERE Id=375;
UPDATE instance_dungeon_encounters SET EncounterName4='Der Prophet Tharon\'ja' WHERE Id=376;

UPDATE instance_dungeon_encounters SET EncounterName4='Verflüssigte Ablagerung' WHERE Id=378;
UPDATE instance_dungeon_encounters SET EncounterName4='Grubbis' WHERE Id=379;
UPDATE instance_dungeon_encounters SET EncounterName4='Elektrokutor 6000' WHERE Id=380;
UPDATE instance_dungeon_encounters SET EncounterName4='Meuteverprügler 9-60' WHERE Id=381;
UPDATE instance_dungeon_encounters SET EncounterName4='Robogenieur Thermadraht' WHERE Id=382;
UPDATE instance_dungeon_encounters SET EncounterName4='Slad\'ran' WHERE Id=383;
UPDATE instance_dungeon_encounters SET EncounterName4='Slad\'ran' WHERE Id=384;
UPDATE instance_dungeon_encounters SET EncounterName4='Koloss der Drakkari' WHERE Id=385;
UPDATE instance_dungeon_encounters SET EncounterName4='Koloss der Drakkari' WHERE Id=386;
UPDATE instance_dungeon_encounters SET EncounterName4='Moorabi' WHERE Id=387;
UPDATE instance_dungeon_encounters SET EncounterName4='Moorabi' WHERE Id=388;
UPDATE instance_dungeon_encounters SET EncounterName4='Der wilde Eck' WHERE Id=389;
UPDATE instance_dungeon_encounters SET EncounterName4='Gal\'darah' WHERE Id=390;
UPDATE instance_dungeon_encounters SET EncounterName4='Gal\'darah' WHERE Id=391;
UPDATE instance_dungeon_encounters SET EncounterName4='Wachhabender Gargolmar' WHERE Id=392;
UPDATE instance_dungeon_encounters SET EncounterName4='Wachhabender Gargolmar' WHERE Id=393;
UPDATE instance_dungeon_encounters SET EncounterName4='Omor der Narbenlose' WHERE Id=394;
UPDATE instance_dungeon_encounters SET EncounterName4='Omor der Narbenlose' WHERE Id=395;
UPDATE instance_dungeon_encounters SET EncounterName4='Vazruden der Herold' WHERE Id=396;
UPDATE instance_dungeon_encounters SET EncounterName4='Vazruden der Herold' WHERE Id=397;

UPDATE instance_dungeon_encounters SET EncounterName4='Der Schöpfer' WHERE Id=401;
UPDATE instance_dungeon_encounters SET EncounterName4='Der Schöpfer' WHERE Id=402;
UPDATE instance_dungeon_encounters SET EncounterName4='Broggok' WHERE Id=403;
UPDATE instance_dungeon_encounters SET EncounterName4='Broggok' WHERE Id=404;
UPDATE instance_dungeon_encounters SET EncounterName4='Keli\'dan der Zerstörer' WHERE Id=405;
UPDATE instance_dungeon_encounters SET EncounterName4='Keli\'dan der Zerstörer' WHERE Id=406;
UPDATE instance_dungeon_encounters SET EncounterName4='Großhexenmeister Nethekurse' WHERE Id=407;
UPDATE instance_dungeon_encounters SET EncounterName4='Großhexenmeister Nethekurse' WHERE Id=408;
UPDATE instance_dungeon_encounters SET EncounterName4='Blutwache Porung' WHERE Id=409;
UPDATE instance_dungeon_encounters SET EncounterName4='Kriegshetzer O\'mrogg' WHERE Id=410;
UPDATE instance_dungeon_encounters SET EncounterName4='Kriegshetzer O\'mrogg' WHERE Id=411;
UPDATE instance_dungeon_encounters SET EncounterName4='Kriegshäuptling Kargath Messerfaust' WHERE Id=412;
UPDATE instance_dungeon_encounters SET EncounterName4='Kriegshäuptling Kargath Messerfaust' WHERE Id=413;
UPDATE instance_dungeon_encounters SET EncounterName4='Selin Feuerherz' WHERE Id=414;
UPDATE instance_dungeon_encounters SET EncounterName4='Selin Feuerherz' WHERE Id=415;
UPDATE instance_dungeon_encounters SET EncounterName4='Vexallus' WHERE Id=416;
UPDATE instance_dungeon_encounters SET EncounterName4='Vexallus' WHERE Id=417;
UPDATE instance_dungeon_encounters SET EncounterName4='Priesterin Delrissa' WHERE Id=418;
UPDATE instance_dungeon_encounters SET EncounterName4='Priesterin Delrissa' WHERE Id=419;
UPDATE instance_dungeon_encounters SET EncounterName4='Kael\'thas Sonnenwanderer' WHERE Id=420;
UPDATE instance_dungeon_encounters SET EncounterName4='Kael\'thas Sonnenwanderer' WHERE Id=421;
UPDATE instance_dungeon_encounters SET EncounterName4='Noxxion' WHERE Id=422;
UPDATE instance_dungeon_encounters SET EncounterName4='Schlingwurzler' WHERE Id=423;
UPDATE instance_dungeon_encounters SET EncounterName4='Lord Schlangenzunge' WHERE Id=424;
UPDATE instance_dungeon_encounters SET EncounterName4='Celebras der Verfluchte' WHERE Id=425;
UPDATE instance_dungeon_encounters SET EncounterName4='Erdrutsch' WHERE Id=426;
UPDATE instance_dungeon_encounters SET EncounterName4='Tüftler Gizlock' WHERE Id=427;
UPDATE instance_dungeon_encounters SET EncounterName4='Faulschnapper' WHERE Id=428;
UPDATE instance_dungeon_encounters SET EncounterName4='Prinzessin Theradras' WHERE Id=429;
UPDATE instance_dungeon_encounters SET EncounterName4='Flintauge' WHERE Id=430;
UPDATE instance_dungeon_encounters SET EncounterName4='Taragaman der Hungerleider' WHERE Id=431;
UPDATE instance_dungeon_encounters SET EncounterName4='Jergosh der Herbeirufer' WHERE Id=432;
UPDATE instance_dungeon_encounters SET EncounterName4='Bazzalan' WHERE Id=433;
UPDATE instance_dungeon_encounters SET EncounterName4='Tuten\'kash' WHERE Id=434;
UPDATE instance_dungeon_encounters SET EncounterName4='Mordresh Feuerauge' WHERE Id=435;
UPDATE instance_dungeon_encounters SET EncounterName4='Nimmersatt' WHERE Id=436;
UPDATE instance_dungeon_encounters SET EncounterName4='Amnennar der Kältebringer' WHERE Id=437;
UPDATE instance_dungeon_encounters SET EncounterName4='Roogug' WHERE Id=438;
UPDATE instance_dungeon_encounters SET EncounterName4='Aggem Dornfluch' WHERE Id=439;
UPDATE instance_dungeon_encounters SET EncounterName4='Todessprecher Jargba' WHERE Id=440;
UPDATE instance_dungeon_encounters SET EncounterName4='Oberanführer Rammhauer' WHERE Id=441;

UPDATE instance_dungeon_encounters SET EncounterName4='Charlga Klingenflanke' WHERE Id=443;
UPDATE instance_dungeon_encounters SET EncounterName4='Befrager Vishas' WHERE Id=444;
UPDATE instance_dungeon_encounters SET EncounterName4='Blutmagier Thalnos' WHERE Id=445;
UPDATE instance_dungeon_encounters SET EncounterName4='Hundemeister Loksey' WHERE Id=446;
UPDATE instance_dungeon_encounters SET EncounterName4='Arkanist Doan' WHERE Id=447;
UPDATE instance_dungeon_encounters SET EncounterName4='Herod' WHERE Id=448;
UPDATE instance_dungeon_encounters SET EncounterName4='Hochinquisitor Schönufer' WHERE Id=449;
UPDATE instance_dungeon_encounters SET EncounterName4='Hochinquisitorin Weißsträhne' WHERE Id=450;
UPDATE instance_dungeon_encounters SET EncounterName4='Kirtonos der Herold' WHERE Id=451;
UPDATE instance_dungeon_encounters SET EncounterName4='Jandice Barov' WHERE Id=452;
UPDATE instance_dungeon_encounters SET EncounterName4='Blutrippe' WHERE Id=453;
UPDATE instance_dungeon_encounters SET EncounterName4='Marduk Schwarzborn' WHERE Id=454;
UPDATE instance_dungeon_encounters SET EncounterName4='Vectus' WHERE Id=455;
UPDATE instance_dungeon_encounters SET EncounterName4='Ras Frostraunen' WHERE Id=456;
UPDATE instance_dungeon_encounters SET EncounterName4='Instrukteurin Malicia' WHERE Id=457;
UPDATE instance_dungeon_encounters SET EncounterName4='Doktor Theolen Krastinov' WHERE Id=458;
UPDATE instance_dungeon_encounters SET EncounterName4='Hüter des Wissens Polkelt' WHERE Id=459;
UPDATE instance_dungeon_encounters SET EncounterName4='Der Verschlinger' WHERE Id=460;
UPDATE instance_dungeon_encounters SET EncounterName4='Lord Alexei Barov' WHERE Id=461;
UPDATE instance_dungeon_encounters SET EncounterName4='Lady Illucia Barov' WHERE Id=462;
UPDATE instance_dungeon_encounters SET EncounterName4='Dunkelmeister Gandling' WHERE Id=463;
UPDATE instance_dungeon_encounters SET EncounterName4='Rotkralle' WHERE Id=464;
UPDATE instance_dungeon_encounters SET EncounterName4='Klingenklaue der Metzger' WHERE Id=465;
UPDATE instance_dungeon_encounters SET EncounterName4='Baron Silberlein' WHERE Id=466;
UPDATE instance_dungeon_encounters SET EncounterName4='Kommandant Grüntal' WHERE Id=467;
UPDATE instance_dungeon_encounters SET EncounterName4='Odo der Blindseher' WHERE Id=468;
UPDATE instance_dungeon_encounters SET EncounterName4='Fenrus der Verschlinger' WHERE Id=469;
UPDATE instance_dungeon_encounters SET EncounterName4='Wolfmeister Nandos' WHERE Id=470;
UPDATE instance_dungeon_encounters SET EncounterName4='Erzmagier Arugal' WHERE Id=471;
UPDATE instance_dungeon_encounters SET EncounterName4='Der Unverziehene' WHERE Id=472;
UPDATE instance_dungeon_encounters SET EncounterName4='Herdsinger Forresten' WHERE Id=473;
UPDATE instance_dungeon_encounters SET EncounterName4='Timmy der Grausame' WHERE Id=474;
UPDATE instance_dungeon_encounters SET EncounterName4='Kanonenmeister Willey' WHERE Id=475;
UPDATE instance_dungeon_encounters SET EncounterName4='Malor der Eifrige' WHERE Id=476;
UPDATE instance_dungeon_encounters SET EncounterName4='Archivar Galford' WHERE Id=477;
UPDATE instance_dungeon_encounters SET EncounterName4='Balnazzar' WHERE Id=478;
UPDATE instance_dungeon_encounters SET EncounterName4='Baroness Anastari' WHERE Id=479;
UPDATE instance_dungeon_encounters SET EncounterName4='Nerub\'enkan' WHERE Id=480;
UPDATE instance_dungeon_encounters SET EncounterName4='Maleki der Leichenblasse' WHERE Id=481;
UPDATE instance_dungeon_encounters SET EncounterName4='Magistrat Barthilas' WHERE Id=482;
UPDATE instance_dungeon_encounters SET EncounterName4='Ramstein der Verschlinger' WHERE Id=483;
UPDATE instance_dungeon_encounters SET EncounterName4='Baron Totenschwur' WHERE Id=484;
UPDATE instance_dungeon_encounters SET EncounterName4='Atal\'alarion' WHERE Id=485;
UPDATE instance_dungeon_encounters SET EncounterName4='Traumsense' WHERE Id=486;
UPDATE instance_dungeon_encounters SET EncounterName4='Wirker' WHERE Id=487;
UPDATE instance_dungeon_encounters SET EncounterName4='Jammal\'an der Prophet' WHERE Id=488;

UPDATE instance_dungeon_encounters SET EncounterName4='Morphaz' WHERE Id=490;
UPDATE instance_dungeon_encounters SET EncounterName4='Hazzas' WHERE Id=491;
UPDATE instance_dungeon_encounters SET EncounterName4='Avatar von Hakkar' WHERE Id=492;
UPDATE instance_dungeon_encounters SET EncounterName4='Eranikus\' Schemen' WHERE Id=493;
UPDATE instance_dungeon_encounters SET EncounterName4='Zereketh der Unabhängige' WHERE Id=494;
UPDATE instance_dungeon_encounters SET EncounterName4='Zereketh der Unabhängige' WHERE Id=495;
UPDATE instance_dungeon_encounters SET EncounterName4='Dalliah die Verdammnisverkünderin' WHERE Id=496;
UPDATE instance_dungeon_encounters SET EncounterName4='Dalliah die Verdammnisverkünderin' WHERE Id=497;
UPDATE instance_dungeon_encounters SET EncounterName4='Zornseher Soccothrates' WHERE Id=498;
UPDATE instance_dungeon_encounters SET EncounterName4='Zornseher Soccothrates' WHERE Id=499;
UPDATE instance_dungeon_encounters SET EncounterName4='Herold Horizontiss' WHERE Id=500;
UPDATE instance_dungeon_encounters SET EncounterName4='Herold Horizontiss' WHERE Id=501;
UPDATE instance_dungeon_encounters SET EncounterName4='Kommandant Sarannis' WHERE Id=502;

UPDATE instance_dungeon_encounters SET EncounterName4='Kommandant Sarannis' WHERE Id=504;
UPDATE instance_dungeon_encounters SET EncounterName4='Hochbotaniker Freywinn' WHERE Id=505;
UPDATE instance_dungeon_encounters SET EncounterName4='Hochbotaniker Freywinn' WHERE Id=506;
UPDATE instance_dungeon_encounters SET EncounterName4='Dorngrin der Hüter' WHERE Id=507;
UPDATE instance_dungeon_encounters SET EncounterName4='Dorngrin der Hüter' WHERE Id=508;
UPDATE instance_dungeon_encounters SET EncounterName4='Laj' WHERE Id=509;
UPDATE instance_dungeon_encounters SET EncounterName4='Laj' WHERE Id=510;
UPDATE instance_dungeon_encounters SET EncounterName4='Warpzweig' WHERE Id=511;
UPDATE instance_dungeon_encounters SET EncounterName4='Warpzweig' WHERE Id=512;
UPDATE instance_dungeon_encounters SET EncounterName4='Mechanolord Kapazitus' WHERE Id=513;
UPDATE instance_dungeon_encounters SET EncounterName4='Mechanolord Kapazitus' WHERE Id=514;
UPDATE instance_dungeon_encounters SET EncounterName4='Nethermantin Sepethrea' WHERE Id=515;
UPDATE instance_dungeon_encounters SET EncounterName4='Nethermantin Sepethrea' WHERE Id=516;
UPDATE instance_dungeon_encounters SET EncounterName4='Pathaleon der Kalkulator' WHERE Id=517;
UPDATE instance_dungeon_encounters SET EncounterName4='Pathaleon der Kalkulator' WHERE Id=518;
UPDATE instance_dungeon_encounters SET EncounterName4='Eingefrorener Kommandant' WHERE Id=519;
UPDATE instance_dungeon_encounters SET EncounterName4='Großmagistrix Telestra' WHERE Id=520;
UPDATE instance_dungeon_encounters SET EncounterName4='Großmagistrix Telestra' WHERE Id=521;
UPDATE instance_dungeon_encounters SET EncounterName4='Anomalus' WHERE Id=522;
UPDATE instance_dungeon_encounters SET EncounterName4='Anomalus' WHERE Id=523;
UPDATE instance_dungeon_encounters SET EncounterName4='Ormorok der Baumformer' WHERE Id=524;
UPDATE instance_dungeon_encounters SET EncounterName4='Ormorok der Baumformer' WHERE Id=525;
UPDATE instance_dungeon_encounters SET EncounterName4='Keristrasza' WHERE Id=526;
UPDATE instance_dungeon_encounters SET EncounterName4='Keristrasza' WHERE Id=527;
UPDATE instance_dungeon_encounters SET EncounterName4='Drakos der Befrager' WHERE Id=528;
UPDATE instance_dungeon_encounters SET EncounterName4='Drakos der Befrager' WHERE Id=529;
UPDATE instance_dungeon_encounters SET EncounterName4='Varos Wolkenwanderer' WHERE Id=530;
UPDATE instance_dungeon_encounters SET EncounterName4='Varos Wolkenwanderer' WHERE Id=531;
UPDATE instance_dungeon_encounters SET EncounterName4='Magierlord Urom' WHERE Id=532;
UPDATE instance_dungeon_encounters SET EncounterName4='Magierlord Urom' WHERE Id=533;
UPDATE instance_dungeon_encounters SET EncounterName4='Leywächter Eregos' WHERE Id=534;
UPDATE instance_dungeon_encounters SET EncounterName4='Leywächter Eregos' WHERE Id=535;
UPDATE instance_dungeon_encounters SET EncounterName4='Targorr der Schreckliche' WHERE Id=536;
UPDATE instance_dungeon_encounters SET EncounterName4='Kam Tiefenzorn' WHERE Id=537;
UPDATE instance_dungeon_encounters SET EncounterName4='Hamhock' WHERE Id=538;
UPDATE instance_dungeon_encounters SET EncounterName4='Bazil Thredd' WHERE Id=539;
UPDATE instance_dungeon_encounters SET EncounterName4='Dextren Ward' WHERE Id=540;
UPDATE instance_dungeon_encounters SET EncounterName4='Erster Gefangener' WHERE Id=541;
UPDATE instance_dungeon_encounters SET EncounterName4='Erster Gefangener' WHERE Id=542;
UPDATE instance_dungeon_encounters SET EncounterName4='Zweiter Gefangener' WHERE Id=543;
UPDATE instance_dungeon_encounters SET EncounterName4='Zweiter Gefangener' WHERE Id=544;
UPDATE instance_dungeon_encounters SET EncounterName4='Cyanigosa' WHERE Id=545;
UPDATE instance_dungeon_encounters SET EncounterName4='Cyanigosa' WHERE Id=546;
UPDATE instance_dungeon_encounters SET EncounterName4='Revelosh' WHERE Id=547;
UPDATE instance_dungeon_encounters SET EncounterName4='Die verlorenen Zwerge' WHERE Id=548;
UPDATE instance_dungeon_encounters SET EncounterName4='Ironaya' WHERE Id=549;

UPDATE instance_dungeon_encounters SET EncounterName4='Uralter Steinbewahrer' WHERE Id=551;
UPDATE instance_dungeon_encounters SET EncounterName4='Galgann Feuerhammer' WHERE Id=552;
UPDATE instance_dungeon_encounters SET EncounterName4='Grimlok' WHERE Id=553;
UPDATE instance_dungeon_encounters SET EncounterName4='Archaedas' WHERE Id=554;
UPDATE instance_dungeon_encounters SET EncounterName4='General Bjarngrim' WHERE Id=555;
UPDATE instance_dungeon_encounters SET EncounterName4='General Bjarngrim' WHERE Id=556;
UPDATE instance_dungeon_encounters SET EncounterName4='Volkhan' WHERE Id=557;
UPDATE instance_dungeon_encounters SET EncounterName4='Volkhan' WHERE Id=558;
UPDATE instance_dungeon_encounters SET EncounterName4='Ionar' WHERE Id=559;
UPDATE instance_dungeon_encounters SET EncounterName4='Ionar' WHERE Id=560;
UPDATE instance_dungeon_encounters SET EncounterName4='Loken' WHERE Id=561;
UPDATE instance_dungeon_encounters SET EncounterName4='Loken' WHERE Id=562;
UPDATE instance_dungeon_encounters SET EncounterName4='Krystallus' WHERE Id=563;
UPDATE instance_dungeon_encounters SET EncounterName4='Krystallus' WHERE Id=564;
UPDATE instance_dungeon_encounters SET EncounterName4='Maid der Trauer' WHERE Id=565;
UPDATE instance_dungeon_encounters SET EncounterName4='Maid der Trauer' WHERE Id=566;
UPDATE instance_dungeon_encounters SET EncounterName4='Tribunal der Zeitalter' WHERE Id=567;
UPDATE instance_dungeon_encounters SET EncounterName4='Tribunal der Zeitalter' WHERE Id=568;
UPDATE instance_dungeon_encounters SET EncounterName4='Sjonnir der Eisenformer' WHERE Id=569;
UPDATE instance_dungeon_encounters SET EncounterName4='Sjonnir der Eisenformer' WHERE Id=570;
UPDATE instance_dungeon_encounters SET EncounterName4='Prinz Keleseth' WHERE Id=571;
UPDATE instance_dungeon_encounters SET EncounterName4='Prinz Keleseth' WHERE Id=572;
UPDATE instance_dungeon_encounters SET EncounterName4='Skarvald & Dalronn' WHERE Id=573;
UPDATE instance_dungeon_encounters SET EncounterName4='Skarvald & Dalronn' WHERE Id=574;
UPDATE instance_dungeon_encounters SET EncounterName4='Ingvar der Brandschatzer' WHERE Id=575;
UPDATE instance_dungeon_encounters SET EncounterName4='Ingvar der Brandschatzer' WHERE Id=576;
UPDATE instance_dungeon_encounters SET EncounterName4='Svala Grabesleid' WHERE Id=577;
UPDATE instance_dungeon_encounters SET EncounterName4='Svala Grabesleid' WHERE Id=578;
UPDATE instance_dungeon_encounters SET EncounterName4='Gortok Bleichhuf' WHERE Id=579;
UPDATE instance_dungeon_encounters SET EncounterName4='Gortok Bleichhuf' WHERE Id=580;
UPDATE instance_dungeon_encounters SET EncounterName4='Skadi der Skrupellose' WHERE Id=581;
UPDATE instance_dungeon_encounters SET EncounterName4='Skadi der Skrupellose' WHERE Id=582;
UPDATE instance_dungeon_encounters SET EncounterName4='König Ymiron' WHERE Id=583;
UPDATE instance_dungeon_encounters SET EncounterName4='König Ymiron' WHERE Id=584;
UPDATE instance_dungeon_encounters SET EncounterName4='Lady Anacondra' WHERE Id=585;
UPDATE instance_dungeon_encounters SET EncounterName4='Lord Kobrahn' WHERE Id=586;
UPDATE instance_dungeon_encounters SET EncounterName4='Kresh' WHERE Id=587;
UPDATE instance_dungeon_encounters SET EncounterName4='Lord Pythas' WHERE Id=588;
UPDATE instance_dungeon_encounters SET EncounterName4='Skum' WHERE Id=589;
UPDATE instance_dungeon_encounters SET EncounterName4='Lord Serpentis' WHERE Id=590;
UPDATE instance_dungeon_encounters SET EncounterName4='Verdan der Ewiglebende' WHERE Id=591;
UPDATE instance_dungeon_encounters SET EncounterName4='Mutanus der Verschlinger' WHERE Id=592;
UPDATE instance_dungeon_encounters SET EncounterName4='Wasserbeschwörerin Velratha' WHERE Id=593;
UPDATE instance_dungeon_encounters SET EncounterName4='Gahz\'rilla' WHERE Id=594;
UPDATE instance_dungeon_encounters SET EncounterName4='Antu\'sul' WHERE Id=595;
UPDATE instance_dungeon_encounters SET EncounterName4='Theka der Märtyrer' WHERE Id=596;
UPDATE instance_dungeon_encounters SET EncounterName4='Hexendoktor Zum\'rah' WHERE Id=597;
UPDATE instance_dungeon_encounters SET EncounterName4='Nekrum der Ausweider' WHERE Id=598;
UPDATE instance_dungeon_encounters SET EncounterName4='Schattenpriester Sezz\'ziz' WHERE Id=599;
UPDATE instance_dungeon_encounters SET EncounterName4='Häuptling Ukorz Sandskalp' WHERE Id=600;
UPDATE instance_dungeon_encounters SET EncounterName4='Oberster Kriegsfürst Naj\'entus' WHERE Id=601;
UPDATE instance_dungeon_encounters SET EncounterName4='Supremus' WHERE Id=602;
UPDATE instance_dungeon_encounters SET EncounterName4='Akamas Schemen' WHERE Id=603;
UPDATE instance_dungeon_encounters SET EncounterName4='Teron Blutschatten' WHERE Id=604;
UPDATE instance_dungeon_encounters SET EncounterName4='Gurtogg Siedeblut' WHERE Id=605;
UPDATE instance_dungeon_encounters SET EncounterName4='Reliquiar der Seelen' WHERE Id=606;
UPDATE instance_dungeon_encounters SET EncounterName4='Mutter Shahraz' WHERE Id=607;
UPDATE instance_dungeon_encounters SET EncounterName4='Der Rat der Illidari' WHERE Id=608;
UPDATE instance_dungeon_encounters SET EncounterName4='Illidan Sturmgrimm' WHERE Id=609;
UPDATE instance_dungeon_encounters SET EncounterName4='Feuerkralle der Ungezähmte' WHERE Id=610;
UPDATE instance_dungeon_encounters SET EncounterName4='Vaelastrasz der Verdorbene' WHERE Id=611;
UPDATE instance_dungeon_encounters SET EncounterName4='Brutwächter Dreschbringer' WHERE Id=612;
UPDATE instance_dungeon_encounters SET EncounterName4='Feuerschwinge' WHERE Id=613;
UPDATE instance_dungeon_encounters SET EncounterName4='Schattenschwinge' WHERE Id=614;
UPDATE instance_dungeon_encounters SET EncounterName4='Flammenmaul' WHERE Id=615;
UPDATE instance_dungeon_encounters SET EncounterName4='Chromaggus' WHERE Id=616;
UPDATE instance_dungeon_encounters SET EncounterName4='Nefarian' WHERE Id=617;
UPDATE instance_dungeon_encounters SET EncounterName4='Furor Winterfrost' WHERE Id=618;
UPDATE instance_dungeon_encounters SET EncounterName4='Anetheron' WHERE Id=619;
UPDATE instance_dungeon_encounters SET EncounterName4='Kaz\'rogal' WHERE Id=620;
UPDATE instance_dungeon_encounters SET EncounterName4='Azgalor' WHERE Id=621;
UPDATE instance_dungeon_encounters SET EncounterName4='Archimonde' WHERE Id=622;
UPDATE instance_dungeon_encounters SET EncounterName4='Hydross der Unstete' WHERE Id=623;
UPDATE instance_dungeon_encounters SET EncounterName4='Das Grauen aus der Tiefe' WHERE Id=624;
UPDATE instance_dungeon_encounters SET EncounterName4='Leotheras der Blinde' WHERE Id=625;
UPDATE instance_dungeon_encounters SET EncounterName4='Tiefenlord Karathress' WHERE Id=626;
UPDATE instance_dungeon_encounters SET EncounterName4='Morogrim Gezeitenwandler' WHERE Id=627;
UPDATE instance_dungeon_encounters SET EncounterName4='Lady Vashj' WHERE Id=628;
UPDATE instance_dungeon_encounters SET EncounterName4='Bestien von Nordened' WHERE Id=629;
UPDATE instance_dungeon_encounters SET EncounterName4='Bestien von Nordened' WHERE Id=630;
UPDATE instance_dungeon_encounters SET EncounterName4='Bestien von Nordened' WHERE Id=631;
UPDATE instance_dungeon_encounters SET EncounterName4='Bestien von Nordened' WHERE Id=632;
UPDATE instance_dungeon_encounters SET EncounterName4='Lord Jaraxxus' WHERE Id=633;
UPDATE instance_dungeon_encounters SET EncounterName4='Lord Jaraxxus' WHERE Id=634;
UPDATE instance_dungeon_encounters SET EncounterName4='Lord Jaraxxus' WHERE Id=635;
UPDATE instance_dungeon_encounters SET EncounterName4='Lord Jaraxxus' WHERE Id=636;
UPDATE instance_dungeon_encounters SET EncounterName4='Fraktionschampions' WHERE Id=637;
UPDATE instance_dungeon_encounters SET EncounterName4='Fraktionschampions' WHERE Id=638;
UPDATE instance_dungeon_encounters SET EncounterName4='Fraktionschampions' WHERE Id=639;
UPDATE instance_dungeon_encounters SET EncounterName4='Fraktionschampions' WHERE Id=640;
UPDATE instance_dungeon_encounters SET EncounterName4='Zwillingsval\'kyr' WHERE Id=641;
UPDATE instance_dungeon_encounters SET EncounterName4='Zwillingsval\'kyr' WHERE Id=642;
UPDATE instance_dungeon_encounters SET EncounterName4='Zwillingsval\'kyr' WHERE Id=643;
UPDATE instance_dungeon_encounters SET EncounterName4='Zwillingsval\'kyr' WHERE Id=644;
UPDATE instance_dungeon_encounters SET EncounterName4='Anub\'arak' WHERE Id=645;
UPDATE instance_dungeon_encounters SET EncounterName4='Anub\'arak' WHERE Id=646;
UPDATE instance_dungeon_encounters SET EncounterName4='Anub\'arak' WHERE Id=647;
UPDATE instance_dungeon_encounters SET EncounterName4='Anub\'arak' WHERE Id=648;
UPDATE instance_dungeon_encounters SET EncounterName4='Hochkönig Maulgar' WHERE Id=649;
UPDATE instance_dungeon_encounters SET EncounterName4='Gruul der Drachenschlächter' WHERE Id=650;
UPDATE instance_dungeon_encounters SET EncounterName4='Magtheridon' WHERE Id=651;
UPDATE instance_dungeon_encounters SET EncounterName4='Attumen der Jäger' WHERE Id=652;
UPDATE instance_dungeon_encounters SET EncounterName4='Moroes' WHERE Id=653;
UPDATE instance_dungeon_encounters SET EncounterName4='Tugendhafte Maid' WHERE Id=654;
UPDATE instance_dungeon_encounters SET EncounterName4='Die Opernvorstellung' WHERE Id=655;
UPDATE instance_dungeon_encounters SET EncounterName4='Der Kurator' WHERE Id=656;
UPDATE instance_dungeon_encounters SET EncounterName4='Terestian Siechhuf' WHERE Id=657;
UPDATE instance_dungeon_encounters SET EncounterName4='Arans Schemen' WHERE Id=658;
UPDATE instance_dungeon_encounters SET EncounterName4='Nethergroll' WHERE Id=659;
UPDATE instance_dungeon_encounters SET EncounterName4='Das Schachspiel' WHERE Id=660;
UPDATE instance_dungeon_encounters SET EncounterName4='Prinz Malchezaar' WHERE Id=661;
UPDATE instance_dungeon_encounters SET EncounterName4='Schrecken der Nacht' WHERE Id=662;
UPDATE instance_dungeon_encounters SET EncounterName4='Lucifron' WHERE Id=663;
UPDATE instance_dungeon_encounters SET EncounterName4='Magmadar' WHERE Id=664;
UPDATE instance_dungeon_encounters SET EncounterName4='Gehennas' WHERE Id=665;
UPDATE instance_dungeon_encounters SET EncounterName4='Garr' WHERE Id=666;
UPDATE instance_dungeon_encounters SET EncounterName4='Shazzrah' WHERE Id=667;
UPDATE instance_dungeon_encounters SET EncounterName4='Baron Geddon' WHERE Id=668;
UPDATE instance_dungeon_encounters SET EncounterName4='Sulfuronherold' WHERE Id=669;
UPDATE instance_dungeon_encounters SET EncounterName4='Golemagg der Verbrenner' WHERE Id=670;
UPDATE instance_dungeon_encounters SET EncounterName4='Majordomus Exekutus' WHERE Id=671;
UPDATE instance_dungeon_encounters SET EncounterName4='Ragnaros' WHERE Id=672;
UPDATE instance_dungeon_encounters SET EncounterName4='Anub\'Rekhan' WHERE Id=673;
UPDATE instance_dungeon_encounters SET EncounterName4='Anub\'Rekhan' WHERE Id=674;

UPDATE instance_dungeon_encounters SET EncounterName4='Großwitwe Faerlina' WHERE Id=677;
UPDATE instance_dungeon_encounters SET EncounterName4='Großwitwe Faerlina' WHERE Id=678;
UPDATE instance_dungeon_encounters SET EncounterName4='Maexxna' WHERE Id=679;
UPDATE instance_dungeon_encounters SET EncounterName4='Maexxna' WHERE Id=680;
UPDATE instance_dungeon_encounters SET EncounterName4='Noth der Seuchenfürst' WHERE Id=681;
UPDATE instance_dungeon_encounters SET EncounterName4='Noth der Seuchenfürst' WHERE Id=682;
UPDATE instance_dungeon_encounters SET EncounterName4='Heigan der Unreine' WHERE Id=683;
UPDATE instance_dungeon_encounters SET EncounterName4='Heigan der Unreine' WHERE Id=684;
UPDATE instance_dungeon_encounters SET EncounterName4='Loatheb' WHERE Id=685;
UPDATE instance_dungeon_encounters SET EncounterName4='Loatheb' WHERE Id=686;
UPDATE instance_dungeon_encounters SET EncounterName4='Instrukteur Razuvious' WHERE Id=687;

UPDATE instance_dungeon_encounters SET EncounterName4='Instrukteur Razuvious' WHERE Id=689;
UPDATE instance_dungeon_encounters SET EncounterName4='Gothik der Ernter' WHERE Id=690;
UPDATE instance_dungeon_encounters SET EncounterName4='Gothik der Ernter' WHERE Id=691;
UPDATE instance_dungeon_encounters SET EncounterName4='Die vier Reiter' WHERE Id=692;
UPDATE instance_dungeon_encounters SET EncounterName4='Die vier Reiter' WHERE Id=693;
UPDATE instance_dungeon_encounters SET EncounterName4='Flickwerk' WHERE Id=694;
UPDATE instance_dungeon_encounters SET EncounterName4='Flickwerk' WHERE Id=695;
UPDATE instance_dungeon_encounters SET EncounterName4='Grobbulus' WHERE Id=696;
UPDATE instance_dungeon_encounters SET EncounterName4='Grobbulus' WHERE Id=697;
UPDATE instance_dungeon_encounters SET EncounterName4='Gluth' WHERE Id=698;
UPDATE instance_dungeon_encounters SET EncounterName4='Gluth' WHERE Id=699;
UPDATE instance_dungeon_encounters SET EncounterName4='Thaddius' WHERE Id=700;
UPDATE instance_dungeon_encounters SET EncounterName4='Thaddius' WHERE Id=701;
UPDATE instance_dungeon_encounters SET EncounterName4='Saphiron' WHERE Id=702;
UPDATE instance_dungeon_encounters SET EncounterName4='Saphiron' WHERE Id=703;
UPDATE instance_dungeon_encounters SET EncounterName4='Kel\'Thuzad' WHERE Id=704;

UPDATE instance_dungeon_encounters SET EncounterName4='Kel\'Thuzad' WHERE Id=706;
UPDATE instance_dungeon_encounters SET EncounterName4='Onyxia' WHERE Id=707;
UPDATE instance_dungeon_encounters SET EncounterName4='Onyxia' WHERE Id=708;
UPDATE instance_dungeon_encounters SET EncounterName4='Der Prophet Skeram' WHERE Id=709;
UPDATE instance_dungeon_encounters SET EncounterName4='Adel der Silithiden' WHERE Id=710;
UPDATE instance_dungeon_encounters SET EncounterName4='Schlachtwache Sartura' WHERE Id=711;
UPDATE instance_dungeon_encounters SET EncounterName4='Fankriss der Unnachgiebige' WHERE Id=712;
UPDATE instance_dungeon_encounters SET EncounterName4='Viscidus' WHERE Id=713;
UPDATE instance_dungeon_encounters SET EncounterName4='Prinzessin Huhuran' WHERE Id=714;
UPDATE instance_dungeon_encounters SET EncounterName4='Zwillingsimperatoren' WHERE Id=715;
UPDATE instance_dungeon_encounters SET EncounterName4='Ouro' WHERE Id=716;
UPDATE instance_dungeon_encounters SET EncounterName4='C\'Thun' WHERE Id=717;
UPDATE instance_dungeon_encounters SET EncounterName4='Kurinnaxx' WHERE Id=718;
UPDATE instance_dungeon_encounters SET EncounterName4='General Rajaxx' WHERE Id=719;
UPDATE instance_dungeon_encounters SET EncounterName4='Moam' WHERE Id=720;
UPDATE instance_dungeon_encounters SET EncounterName4='Buru der Verschlinger' WHERE Id=721;
UPDATE instance_dungeon_encounters SET EncounterName4='Ayamiss der Jäger' WHERE Id=722;
UPDATE instance_dungeon_encounters SET EncounterName4='Ossirian der Narbenlose' WHERE Id=723;
UPDATE instance_dungeon_encounters SET EncounterName4='Kalecgos' WHERE Id=724;
UPDATE instance_dungeon_encounters SET EncounterName4='Brutallus' WHERE Id=725;
UPDATE instance_dungeon_encounters SET EncounterName4='Teufelsruch' WHERE Id=726;
UPDATE instance_dungeon_encounters SET EncounterName4='Eredarzwillinge' WHERE Id=727;
UPDATE instance_dungeon_encounters SET EncounterName4='M\'uru' WHERE Id=728;
UPDATE instance_dungeon_encounters SET EncounterName4='Kil\'jaeden' WHERE Id=729;
UPDATE instance_dungeon_encounters SET EncounterName4='Al\'ar' WHERE Id=730;
UPDATE instance_dungeon_encounters SET EncounterName4='Leerhäscher' WHERE Id=731;
UPDATE instance_dungeon_encounters SET EncounterName4='Hochastromantin Solarian' WHERE Id=732;
UPDATE instance_dungeon_encounters SET EncounterName4='Kael\'thas Sonnenwanderer' WHERE Id=733;
UPDATE instance_dungeon_encounters SET EncounterName4='Malygos' WHERE Id=734;
UPDATE instance_dungeon_encounters SET EncounterName4='Malygos' WHERE Id=735;
UPDATE instance_dungeon_encounters SET EncounterName4='Tenebron' WHERE Id=736;
UPDATE instance_dungeon_encounters SET EncounterName4='Tenebron' WHERE Id=737;
UPDATE instance_dungeon_encounters SET EncounterName4='Shadron' WHERE Id=738;
UPDATE instance_dungeon_encounters SET EncounterName4='Shadron' WHERE Id=739;
UPDATE instance_dungeon_encounters SET EncounterName4='Vesperon' WHERE Id=740;
UPDATE instance_dungeon_encounters SET EncounterName4='Vesperon' WHERE Id=741;
UPDATE instance_dungeon_encounters SET EncounterName4='Sartharion' WHERE Id=742;
UPDATE instance_dungeon_encounters SET EncounterName4='Sartharion' WHERE Id=743;
UPDATE instance_dungeon_encounters SET EncounterName4='Flammenleviathan' WHERE Id=744;
UPDATE instance_dungeon_encounters SET EncounterName4='Ignis, Meister des Eisenwerks' WHERE Id=745;
UPDATE instance_dungeon_encounters SET EncounterName4='Klingenschuppe' WHERE Id=746;
UPDATE instance_dungeon_encounters SET EncounterName4='XT-002 Dekonstruktor' WHERE Id=747;
UPDATE instance_dungeon_encounters SET EncounterName4='Der Eiserne Rat' WHERE Id=748;
UPDATE instance_dungeon_encounters SET EncounterName4='Kologarn' WHERE Id=749;
UPDATE instance_dungeon_encounters SET EncounterName4='Auriaya' WHERE Id=750;
UPDATE instance_dungeon_encounters SET EncounterName4='Hodir' WHERE Id=751;
UPDATE instance_dungeon_encounters SET EncounterName4='Thorim' WHERE Id=752;
UPDATE instance_dungeon_encounters SET EncounterName4='Freya' WHERE Id=753;
UPDATE instance_dungeon_encounters SET EncounterName4='Mimiron' WHERE Id=754;
UPDATE instance_dungeon_encounters SET EncounterName4='General Vezax' WHERE Id=755;
UPDATE instance_dungeon_encounters SET EncounterName4='Yogg-Saron' WHERE Id=756;
UPDATE instance_dungeon_encounters SET EncounterName4='Algalon der Beobachter' WHERE Id=757;
UPDATE instance_dungeon_encounters SET EncounterName4='Flammenleviathan' WHERE Id=758;
UPDATE instance_dungeon_encounters SET EncounterName4='Ignis, Meister des Eisenwerks' WHERE Id=759;
UPDATE instance_dungeon_encounters SET EncounterName4='Klingenschuppe' WHERE Id=760;
UPDATE instance_dungeon_encounters SET EncounterName4='XT-002 Dekonstruktor' WHERE Id=761;
UPDATE instance_dungeon_encounters SET EncounterName4='Der Eiserne Rat' WHERE Id=762;
UPDATE instance_dungeon_encounters SET EncounterName4='Kologarn' WHERE Id=763;
UPDATE instance_dungeon_encounters SET EncounterName4='Auriaya' WHERE Id=764;
UPDATE instance_dungeon_encounters SET EncounterName4='Hodir' WHERE Id=765;
UPDATE instance_dungeon_encounters SET EncounterName4='Thorim' WHERE Id=766;
UPDATE instance_dungeon_encounters SET EncounterName4='Freya' WHERE Id=767;
UPDATE instance_dungeon_encounters SET EncounterName4='Mimiron' WHERE Id=768;
UPDATE instance_dungeon_encounters SET EncounterName4='General Vezax' WHERE Id=769;
UPDATE instance_dungeon_encounters SET EncounterName4='Yogg-Saron' WHERE Id=770;
UPDATE instance_dungeon_encounters SET EncounterName4='Algalon der Beobachter' WHERE Id=771;
UPDATE instance_dungeon_encounters SET EncounterName4='Archavon der Steinwächter' WHERE Id=772;
UPDATE instance_dungeon_encounters SET EncounterName4='Archavon der Steinwächter' WHERE Id=773;
UPDATE instance_dungeon_encounters SET EncounterName4='Emalon der Sturmwächter' WHERE Id=774;
UPDATE instance_dungeon_encounters SET EncounterName4='Emalon der Sturmwächter' WHERE Id=775;
UPDATE instance_dungeon_encounters SET EncounterName4='Koralon der Flammenwächter' WHERE Id=776;
UPDATE instance_dungeon_encounters SET EncounterName4='Koralon der Flammenwächter' WHERE Id=777;
UPDATE instance_dungeon_encounters SET EncounterName4='Akil\'zon' WHERE Id=778;
UPDATE instance_dungeon_encounters SET EncounterName4='Nalorakk' WHERE Id=779;
UPDATE instance_dungeon_encounters SET EncounterName4='Jan\'alai' WHERE Id=780;
UPDATE instance_dungeon_encounters SET EncounterName4='Halazzi' WHERE Id=781;
UPDATE instance_dungeon_encounters SET EncounterName4='Hexlord Malacrass' WHERE Id=782;
UPDATE instance_dungeon_encounters SET EncounterName4='Zul\'jin' WHERE Id=783;
UPDATE instance_dungeon_encounters SET EncounterName4='Hohepriester Venoxis' WHERE Id=784;
UPDATE instance_dungeon_encounters SET EncounterName4='Hohepriesterin Jeklik' WHERE Id=785;
UPDATE instance_dungeon_encounters SET EncounterName4='Hohepriesterin Mar\'li' WHERE Id=786;
UPDATE instance_dungeon_encounters SET EncounterName4='Blutfürst Mandokir' WHERE Id=787;
UPDATE instance_dungeon_encounters SET EncounterName4='Rand des Wahnsinns' WHERE Id=788;
UPDATE instance_dungeon_encounters SET EncounterName4='Hohepriester Thekal' WHERE Id=789;
UPDATE instance_dungeon_encounters SET EncounterName4='Gahz\'ranka' WHERE Id=790;
UPDATE instance_dungeon_encounters SET EncounterName4='Hohepriesterin Arlokk' WHERE Id=791;
UPDATE instance_dungeon_encounters SET EncounterName4='Jin\'do der Verhexer' WHERE Id=792;
UPDATE instance_dungeon_encounters SET EncounterName4='Hakkar' WHERE Id=793;

UPDATE instance_dungeon_encounters SET EncounterName4='Bronjahm' WHERE Id=829;
UPDATE instance_dungeon_encounters SET EncounterName4='Bronjahm' WHERE Id=830;
UPDATE instance_dungeon_encounters SET EncounterName4='Verschlinger der Seelen' WHERE Id=831;
UPDATE instance_dungeon_encounters SET EncounterName4='Verschlinger der Seelen' WHERE Id=832;
UPDATE instance_dungeon_encounters SET EncounterName4='Schmiedemeister Garfrost' WHERE Id=833;
UPDATE instance_dungeon_encounters SET EncounterName4='Schmiedemeister Garfrost' WHERE Id=834;
UPDATE instance_dungeon_encounters SET EncounterName4='Krick' WHERE Id=835;
UPDATE instance_dungeon_encounters SET EncounterName4='Krick' WHERE Id=836;
UPDATE instance_dungeon_encounters SET EncounterName4='Geißelfürst Tyrannus' WHERE Id=837;
UPDATE instance_dungeon_encounters SET EncounterName4='Geißelfürst Tyrannus' WHERE Id=838;
UPDATE instance_dungeon_encounters SET EncounterName4='Marwyn' WHERE Id=839;
UPDATE instance_dungeon_encounters SET EncounterName4='Marwyn' WHERE Id=840;
UPDATE instance_dungeon_encounters SET EncounterName4='Falric' WHERE Id=841;
UPDATE instance_dungeon_encounters SET EncounterName4='Falric' WHERE Id=842;
UPDATE instance_dungeon_encounters SET EncounterName4='Arthas entflohen' WHERE Id=843;
UPDATE instance_dungeon_encounters SET EncounterName4='Arthas entflohen' WHERE Id=844;
UPDATE instance_dungeon_encounters SET EncounterName4='Lord Mark\'gar' WHERE Id=845;
UPDATE instance_dungeon_encounters SET EncounterName4='Lady Todeswisper' WHERE Id=846;
UPDATE instance_dungeon_encounters SET EncounterName4='Kanonenschiffsschlacht von Eiskrone' WHERE Id=847;
UPDATE instance_dungeon_encounters SET EncounterName4='Todesbringer Saurfang' WHERE Id=848;
UPDATE instance_dungeon_encounters SET EncounterName4='Fauldarm' WHERE Id=849;
UPDATE instance_dungeon_encounters SET EncounterName4='Modermiene' WHERE Id=850;
UPDATE instance_dungeon_encounters SET EncounterName4='Professor Seuchenmord' WHERE Id=851;
UPDATE instance_dungeon_encounters SET EncounterName4='Rat des Blutes' WHERE Id=852;
UPDATE instance_dungeon_encounters SET EncounterName4='Blutkönigin Lana\'thel' WHERE Id=853;
UPDATE instance_dungeon_encounters SET EncounterName4='Valithria Traumwandler' WHERE Id=854;
UPDATE instance_dungeon_encounters SET EncounterName4='Sindragosa' WHERE Id=855;
UPDATE instance_dungeon_encounters SET EncounterName4='Der Lichkönig' WHERE Id=856;
UPDATE instance_dungeon_encounters SET EncounterName4='Lord Mark\'gar' WHERE Id=857;
UPDATE instance_dungeon_encounters SET EncounterName4='Lady Todeswisper' WHERE Id=858;
UPDATE instance_dungeon_encounters SET EncounterName4='Kanonenschiffsschlacht von Eiskrone' WHERE Id=859;
UPDATE instance_dungeon_encounters SET EncounterName4='Todesbringer Saurfang' WHERE Id=860;
UPDATE instance_dungeon_encounters SET EncounterName4='Fauldarm' WHERE Id=861;
UPDATE instance_dungeon_encounters SET EncounterName4='Modermiene' WHERE Id=862;
UPDATE instance_dungeon_encounters SET EncounterName4='Professor Seuchenmord' WHERE Id=863;
UPDATE instance_dungeon_encounters SET EncounterName4='Rat des Blutes' WHERE Id=864;
UPDATE instance_dungeon_encounters SET EncounterName4='Blutkönigin Lana\'thel' WHERE Id=865;
UPDATE instance_dungeon_encounters SET EncounterName4='Valithria Traumwandler' WHERE Id=866;
UPDATE instance_dungeon_encounters SET EncounterName4='Sindragosa' WHERE Id=867;
UPDATE instance_dungeon_encounters SET EncounterName4='Der Lichkönig' WHERE Id=868;

UPDATE instance_dungeon_encounters SET EncounterName4='Agathelos der Tobende' WHERE Id=883;

UPDATE instance_dungeon_encounters SET EncounterName4='Toravon der Eiswächter' WHERE Id=885;
UPDATE instance_dungeon_encounters SET EncounterName4='Toravon der Eiswächter' WHERE Id=886;
UPDATE instance_dungeon_encounters SET EncounterName4='Halion' WHERE Id=887;
UPDATE instance_dungeon_encounters SET EncounterName4='Halion' WHERE Id=888;
UPDATE instance_dungeon_encounters SET EncounterName4='Baltharus der Kriegsjünger' WHERE Id=889;
UPDATE instance_dungeon_encounters SET EncounterName4='Baltharus der Kriegsjünger' WHERE Id=890;
UPDATE instance_dungeon_encounters SET EncounterName4='Saviana Flammenschlund' WHERE Id=891;
UPDATE instance_dungeon_encounters SET EncounterName4='Saviana Flammenschlund' WHERE Id=892;
UPDATE instance_dungeon_encounters SET EncounterName4='General Zarithrian' WHERE Id=893;
UPDATE instance_dungeon_encounters SET EncounterName4='General Zarithrian' WHERE Id=894;
SET NAMES 'latin1';
