#####  transports  #####

SET NAMES 'utf8';
UPDATE transports SET name='Dampfdruckpapier, Ratschet und Beutebucht (\"Die Launische Minna\")' WHERE entry=20808;
UPDATE transports SET name='Orgrimmar, Durotar und Unterstadt, Tirisfal (\"Die Donnersturm\")' WHERE entry=164871;
UPDATE transports SET name='Orgrimmar, Durotar und Basislager von Grom\'gol, Schlingendorntal (\"Der Eiserne Adler\")' WHERE entry=175080;
UPDATE transports SET name='Hafen von Menethil, Sumpfland und Inseln von Theramore, Düstermarschen (\"Die Lady Mehley\")' WHERE entry=176231;
UPDATE transports SET name='Rut\'theran, Teldrassil und Auberdine, Dunkelküste (\"Die Mondgischt\")' WHERE entry=176244;
UPDATE transports SET name='Hafen von Sturmwind und Auberdine, Dunkelküste (\"Die Bravado\")' WHERE entry=176310;
UPDATE transports SET name='Unterstadt, Tirisfal und Basislager von Grom\'gol, Schlingendorntal (\"Die Prinzessin Violetta\")' WHERE entry=176495;
UPDATE transports SET name='Die vergessene Küste, Feralas und Mondfederfeste, Insel Sardor, Feralas (\"Mondfederfähre\")' WHERE entry=177233;
UPDATE transports SET name='Valaars Steg, Azurmythosinsel und Auberdine, Dunkelküste (\"Elunes Segen\")' WHERE entry=181646;
UPDATE transports SET name='Hafen von Menethil, Sumpfland und Valgarde, Der Heulende Fjord (\"Nordspeer\")' WHERE entry=181688;
UPDATE transports SET name='Unterstadt, Tirisfal und Hafen der Vergeltung, Der Heulende Fjord (\"Die Wolkenkuss\")' WHERE entry=181689;
UPDATE transports SET name='Orgrimmar, Durotar und Kriegshymnenfeste, Boreanische Tundra (\"Die Windesmacht\")' WHERE entry=186238;
UPDATE transports SET name='Westwacht im Heulenden Fjord zum Bombardieren der Piraten (\"Zeppelin\")' WHERE entry=186371;
UPDATE transports SET name='Nicht besteigbar - Kreist im Heulenden Fjord (\"Gnädige Schwester\")' WHERE entry=187038;
UPDATE transports SET name='Unu\'pe, Boreanische Tundra und Hafen Moa\'ki, Drachenöde (\"Wellenreiter\")' WHERE entry=187568;
UPDATE transports SET name='Hafen Moa\'ki und Kamagua (\"Grüne Insel\")' WHERE entry=188511;
UPDATE transports SET name='Hafen von Sturmwind und Valianzfeste, Boreanische Tundra (\"Die Kraken\")' WHERE entry=190536;
UPDATE transports SET name='Orgrimmar, Durotar und Donnerfels, Mulgore (\"Die Zephyr\")' WHERE entry=190549;
UPDATE transports SET name='Nicht besteigbar - Kriegsschiff der Horde patroulliert über Eiskrone (\"Orgrims Hammer\")' WHERE entry=192241;
UPDATE transports SET name='Nicht besteigbar - Kriegsschiff der Allianz patroulliert über Eiskrone (\"Die Himmelsteiler\")' WHERE entry=192242;
UPDATE transports SET name='IOC - Kanonenboot der Allianz' WHERE entry=195121;
UPDATE transports SET name='IOC - Kanonenboot der Horde' WHERE entry=195276;
UPDATE transports SET name='Eiskronenzitadelle (\"Die Himmelsbrecher\")' WHERE entry=201580;
UPDATE transports SET name='Eiskronenzitadelle (\"Orgrims Hammer\")' WHERE entry=201581;
UPDATE transports SET name='Die Himmelsbrecher' WHERE entry=201598;
UPDATE transports SET name='Zeppelin, Horde (\"Die Windesmacht\")(Eiskronenzitadelle)' WHERE entry=201834;
SET NAMES 'latin1';
